### PR TITLE
Two improvements to cocoa MultilineTextInput: disable richtext, and enable undo

### PR DESCRIPTION
**Pull request by bruno-rino**
I found the current cocoa implementation MultilineTextInput lacking:

- When pasting formatted text (e.g. a webpage), the formatting would stay. Since this widget doesn't allow to manipulate the formatting in any way, I think it best to disable it completely.
- The cocoa widget has undo/redo turned of by default

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by freakboy3742** [comment]
Thanks for the contribution. I'm currently travelling for EuroPython, so finding time for PR reviews is a bit difficult; however, from an initial inspection, this looks good. The only thing obvious improvement I can think of would be a test - this change doesn't decrease code coverage, but it would be good to have some form of validation that pasting rich content or executing an undo has the desired behavior. The complication is that the test will need backend probe implementations for all platforms - however, I think we could probably live with a `skip` implementation that explicitly flags that the test hasn't been fully implemented on Windows/GTK etc yet.

**Comment by freakboy3742** [comment]
@bruno-rino As luck would have it, I've just written up an [explanation of the testbed architecture for another PR](https://github.com/beeware/toga/pull/2130#issuecomment-1736443774). A cleaned up version of this should probably be in our contribution guide; I've opened #2137 to track this.

**Comment by mhsmith** [comment]
More details: https://toga.readthedocs.io/en/latest/how-to/contribute-code.html#how-the-testbed-works.

**Comment by bruno-rino** [comment]
I am writing an undo / redo test for macOS. Which approach would be preferable for triggering the undo / redo action:
- emit "cmd+Z" and "cmd+shift+Z"
- use cocoa API (NSUndoManager)

**Comment by freakboy3742** [comment]
> I am writing an undo / redo test for macOS. Which approach would be preferable for triggering the undo / redo action:

Cmd-(shift)-Z seems like the better option to me - we're looking to confirm the action as close to "human" interaction as possible.

**Comment by bruno-rino** [comment]
So... I guess I should have updated my branch beforehand.

**Comment by bruno-rino** [comment]
Replaced with PR https://github.com/beeware/toga/pull/2151

**Pull request closed without merging**
