### PR TITLE
Support for Hiding the titlebar & toolbar

### PR DESCRIPTION
**Pull request by ItsCubeTime**
Adds support for hiding the tool &  titlebar on Windows via new parameters & attributes "show_toolbar" & " show_title_bar" on the Window class.

To allow the arguments from being passed down to Window._impl in toga/core/window.py without upsetting other implementations, Ive added **kwargs at the end of all other implementation's Window class.

See demo project:
https://youtu.be/C91bQ8CU4-w
https://pastebin.com/JFUBYPLv

Would solve https://github.com/beeware/toga/issues/733 & https://github.com/beeware/toga/discussions/1792 for the Windows platform & create a standardized pattern (via the "show_toolbar" & "show_title_bar")  for other platforms to implement the same functionality

### CODE REVIEW

**Comment by ItsCubeTime** [comment]
```
PS C:\Users\olliv\Desktop\Art And Development\toga\toga src build\toga> pre-commit run     
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/PyCQA/isort.
[INFO] Initializing environment for https://github.com/PyCQA/isort:toml.
[INFO] Initializing environment for https://github.com/asottile/pyupgrade.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/PyCQA/flake8.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/PyCQA/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/asottile/pyupgrade.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/PyCQA/flake8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
check toml...........................................(no files to check)Skipped
check yaml...........................................(no files to check)Skipped
check for case conflicts.............................(no files to check)Skipped
check docstring is first.............................(no files to check)Skipped
fix end of files.....................................(no files to check)Skipped
trim trailing whitespace.............................(no files to check)Skipped
isort................................................(no files to check)Skipped
pyupgrade............................................(no files to check)Skipped
black................................................(no files to check)Skipped
flake8...............................................(no files to check)Skipped
PS C:\Users\olliv\Desktop\Art And Development\toga\toga src build\toga> 
```
Am I doing something wrong here? I want it to display the issues that  are being detected by your ci

**Review by freakboy3742 — COMMENTED** [review]
Thanks for the PR. I would have thought the responses on #1792 would have indicated that this was incompatible with the design of Toga; unfortunately, there's nothing in this PR that changes my mind on that. I still don't think this is an idea that is fundamentally compatible with Toga. 

Firstly: if you don't want a toolbar, don't define a toolbar. Toga won't add one unless you define it. There's no need to have a separate option that would allow you to define a toolbar, and then *not* display it. 

Secondly: if, by "toolbar", you mean "menubar" - that's a subject that has come up before (including in the discussion on #733), and I've stated that my preferred approach is a "SimpleApp" base class that is the "bare minimum" version of an application, while still adhering to platform conventions. On an administrative note - keeping language consistent in APIs is a key part of API design - so this kind of detail is *really* important.

Lastly - and most importantly - Toga tries *very* hard to honour native system look and feel. Basic window chrome is one of the most fundamental pieces of system look and feel. This PR seems fundamentally opposed to that as an idea.

Put it this way: If you define an app that has "no titlebar" - how do you maximise the app? How do you minimise the app? How do you close the app? 

If your answer to any of these questions is "I'll put a button in the GUI where I want it, looking like how I want it", then you've fundamentally misunderstood what Toga is trying to do with the API it exposes, and the way that API adheres to local UI/UX conventions.

If your answer to these questions is "the user won't need to, because my app can't be maximized/minimized/be manually closed", my followup question is "how is the user meant to know this"? Default operating system chrome has conventions for communicating this to users - disabling or hiding the default buttons. If you re-invent this wheel, how does the user learn what *your* conventions are?

Toga tries to make apps look native. The mockup you've provided in the Youtube video is decidedly *not* native. My advice to you is that if you're set on completely customising your app's look and feel, then Toga isn't the widget toolkit you're looking for.

On a personal note - this is ultimately a decision that you need to make for your own app, but FWIW: I have *never* seen an app that "re-invents" basic window chrome in a way that makes me glad they did so. It's usually done in service of some sort of skeuomorphism, or an acute case of "Branding" - and neither of those are especially good for the *users* of your app - if only because the developers of these customisations inevitably forget or ignore some basic UX affordance such as accessibility controls.

I'm going to close this PR because I can't see a world in which it will be merged. If you think there is a future for this PR that I'm not seeing, you want to discuss the details, then feel free to start a discussion thread (or, continue the one that you have already started); but keep in mind that you're unlikely to change my mind on the fundamental issue here - that Toga explicitly *isn't* trying to accomodate skeuomorphic and heavily branded UIs.

**Comment by ItsCubeTime** [comment]
Ah, I see. I honestly didn't see those comments until now that you linked them. I will just keep this in my fork, but I do believe Im not alone to want this feature. Its quite common for apps to customize the titlebar. Even Microsofts own VS Code does it.

**Comment by freakboy3742** [comment]
I'm not offended at all - I just don't like wasting volunteer time. You've clearly spent time developing and testing this, and it's time that could have been spent elsewhere (even if that means you're contributing to a different project).

It's also a small piece of begging on my part for developers to stop overriding system default chrome :-)

**Pull request closed without merging**
