### PR TITLE
Fixes #1471 - ensure Selection items are cast to strings

### LINKED ISSUE #1471: Toga.Selection causing crash
**Describe the bug**
toga.Selection causes terminal crash when items property is populated with list of integers.  Exception is not handled, no traceback log on Python either. 

**To Reproduce**
1. Create a list of integers.
2. Create a toga.Selection object and set the items property to the list of integers. 
3. Put the selection object into a box and display on the screen. 
4. App will crash without descriptive exception messaging. 

**Expected behavior**
Data type error message. Windows instead throws a CLI memory corruption error with no traceability back to the widget. 

**Environment:**
 - Operating System: Windows 10, Android 12 (also on virtual android emulators for pixel)
 - Python version: 3.9
 - Software versions:
   - Briefcase:
   - Toga:
   - ...

**Additional context**

### PR DESCRIPTION
**Pull request by jahrules**
Signed-off-by: Gregory Taeger <greg.taeger@gmail.com>

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by jahrules** [comment]
I duplicated the bug and tested the fix. Initially I thought the fix needed to be in the add_items(item) but then I realized that the array was being saved for later usage so I quickly realized I needed to cast the array.

**Comment by jahrules** [comment]
apologies I just noticed that the # of the bug I fixed didnt carry in my PR (it was named in my fork). its #1471

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
Thanks for the PR; however, your original instinct was correct - the issue here is on the usage of the item list, not the initial casting. `Items` are data; the only requirement is that they need to be convertible to a string form. The conversion to string form is an implementation rendering issue, not something that should be preserved in the data for the widget. 

It also looks like the android backend *is* casting the item to string before adding it to the widget; so the underlying problem here is something else.

**Comment by freakboy3742** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
