### PR TITLE
Cast pathlib.Path to string in Image()

### PR DESCRIPTION
**Pull request by shape-warrior-t**
I probably should have announced my intentions to work on this before actually working on it, but ah well.

This pull request aims to implement the functionality described in issue #1294. Currently, `toga.Image` expects to be given a string, and will error if given a `pathlib.Path` object. Under this PR, it will convert the given `path` argument to a string, allowing `pathlib.Path` objects to be used to construct images without having to manually convert to a string.

The `imageview` example has also been modified to add a test case for passing in `pathlib.Path` objects to `toga.Image`.

Potential concerns:
- The PR currently does not do any type checking of the `path` argument, though Toga in general does not do much type checking and it's hard for me to imagine a situation where converting something to a string without type checking could turn out to be a disaster.
- For the example, I just copied the code for the local path and made minor modifications to it. Currently, both image views show the same image `pride-brutus.png`. It might be appropriate to use a different image for the `pathlib.Path` image view.
- I have not updated any documentation, though I'm not sure if there is any documentation to update. The way things are worded in https://toga.readthedocs.io/en/latest/reference/api/resources/images.html, it doesn't actually specify that the path has to be a string.

## PR Checklist:

- [x] All new features have been tested
- [?] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
Thanks for the PR; while this makes the immediate problem go away, this fix is tackling the problem the wrong way. We're moving towards having `Path` as our preferred representation for file paths; if anything, we should be casting to `Path`, not *away* from `Path`. That won't work as a completely naïve fix (as URLs are also valid input), but that's the general direction we should be heading.

**Comment by shape-warrior-t** [comment]
Update: the approach I'm currently going for is that `self.path` should be a `Path` if it represents a local file path and a string if it represents a URL. We do the appropriate type conversions in `__init__`, and in `bind` we check the type of `self.path` to determine how we should use the path.

There might be a whole bunch of things off with this series of changes. Aside from me not being sure about the fundamental approach here, I'm also going to be making some changes to the tests. Either way, please let me know if something isn't right with this iteration of the pull request.

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
This looks like the right approach; the only piece missing now are test cases of the new construction paths.

**Comment by shape-warrior-t** [comment]
Working on that right now, though I'm not very experienced in writing tests, so the approach might be a bit wonky.

Currently, I'm creating three images and assigning them as properties to `self`: one for each of the three ways to specify a path (str file, str url, path file). Then I'll test the file images for how they interact with binding, and all images to make sure `self.image.path` is correct. That currently makes for 5 separate tests.

Is there any way to test `bind` on the URL image? Also, please let me know if this isn't the best way to conduct the tests.

**Comment by shape-warrior-t** [comment]
I'm almost done with everything, though I'm not sure how I would be testing `bind` for the URL image. For now, I'm going to look into the everything surrounding `_action`.

**Comment by shape-warrior-t** [comment]
Alright, I think I'm finally done making changes for now. I found a way to test `bind` on URL images. The testing and logging stuff was a bit of a maze to navigate through, but looking through it gave me a slightly better understanding of Beeware's infrastructure.

This PR is once again in a review-ready state. Hope there are no more issues, but if there are, please let me know.

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
Looks good; Two relatively minor cleanups on the test case and we should be good to merge.

As an aside - I would have made this two modifications myself, but you've submitted this PR from your `main` branch. There's nothing fundamentally *wrong* with that from a git perspective, but Github definitely doesn't play well with PRs submitted from a main branch, and when a PR is fine except for a minor tweak, a project maintainer can't push it the last few metres to completion.

**Review by freakboy3742 — APPROVED** [review]
Looks great! Thanks for the fix!

**Comment by shape-warrior-t** [comment]
Glad to help! Thanks for the help and advice on everything, including the details about `# pragma: nocover` and working on a non-main branch.

**Pull request merged**
