### PR TITLE
Update pack.rst

### PR DESCRIPTION
**Pull request by proneon267**
The previous values were not defined in the library.

The new valid values are added and were tested.

Now, the new values will be valid for anyone following the docs for guidance.

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
Thanks for the PR; however, there appears to be a fundamental misunderstanding here. The lower case versions in this document are correct - the allowable *values* of `display` are `pack` and `none`, not `PACK` and `NONE`. The *Python constants* defining those values are `PACK` and `NONE`. This is definitely something that should be clarified in this documentation; but modifying all the values to be upper case would be misleading.

**Comment by proneon267** [comment]
So, what does that mean for a user looking at the docs? I mean using the lower case values show up as not defined error in python. Also sometimes these error messages show the valid choices in uppercases. Do you intend to create lowercase aliases for the uppercase python constants in future, or something?

**Comment by freakboy3742** [comment]
> So, what does that mean for a user looking at the docs? I mean using the lower case values show up as not defined error in python. 

Yes - because the document is describing valid values as *strings*. `style=Pack(display='none')` is a valid Pack construction. `from toga.style.pack import NONE; style=Pack(display=NONE)` is using a Python symbolic constant that defines the same string.

> Also sometimes these error messages show the valid choices in uppercases. 

Can you give an example of this? I can't say I've seen this behavior.

> Do you intend to create lowercase aliases for the uppercase python constants in future, or something?

That wasn't our intention. The use of `UPPERCASE` to define constants is a fairly consistent convention in programming languages. Adding symbolic constants for `none`, `left`, `right` etc would be consistent with their underlying string values, but would introduce a whole other class of confusion - one that I'd argue is harder to explain, because it is rooted in violating a core idea/style recommendation in the programming language.

I definitely agree this needs to be pointed out more clearly in the docs - but that doesn't change the fact that the actual strings being defined are all in lower case, backed by Python-defined symbolic constants that are upper case.

**Comment by proneon267** [comment]
It seems that there has been a misunderstanding about the api. I will close this pull request and open a new one with appropriate changes. Thanks.

**Pull request closed without merging**
