### PR TITLE
Fixes #387: Accomodate URLs without any mentioned protocol

### LINKED ISSUE #387: Webview doesn't handle urls with scheme absent
## Steps to reproduce

1. Run examples/example4
2. Type the url 'google.com' and click 'Go'
3. No change
4. Type 'https://google.com' and click 'Go'
5. Takes me to Google's homepage

## Expected Behavior

Typing in 'google.com' and hitting 'Go' should change the url to 'https://google.com' and take me to the Google homepage

## Cause

Currently the `WebView.set_url` function only checks whether value is `None` and loads the url

## Proposed Change
1. Either we could change `set_url` signature to include scheme with default as `http` or,
2. We could make `set_url` check whether passed value is valid url
3. Or add elementary substitution logic inside `set_url` method  

Thoughts?

## Your Environment

* Python Version (list the specific version number)
```bash
$ python --version
Python 3.6.4
```
* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

 - [x] Linux
```bash
$ uname -a
Linux hbar 4.15.4-1-ARCH #1 SMP PREEMPT Sat Feb 17 16:01:38 UTC 2018 x86_64 GNU/Linux
```

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [x] gtk (gtk3 3.22.28-1)
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

### PR DESCRIPTION
**Pull request by Donyme**
## PR Checklist:

- [ ] All new features have been tested
- [ ] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by Donyme** [comment]
What else do we need to implement, so as to improve the search url? Or we
need to leave it as it is?

**Comment by freakboy3742** [comment]
@Donyme I need you to *read the discussion on the ticket*. The details you need are all there. 

If you need clarification on what is described there, I'm happy to answer questions. But repeating the discussion there is a waste of *everybody's* time.

**Comment by Donyme** [comment]
I ll look Into dat, sorry for inconvenience

On 10 Mar 2018 11:23 am, "Russell Keith-Magee" <notifications@github.com>
wrote:

@Donyme <https://github.com/donyme> I need you to *read the discussion on
the ticket*. The details you need are all there.

If you need clarification on what is described there, I'm happy to answer
questions. But repeating the discussion there is a waste of *everybody's*
time.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/pybee/toga/pull/398#issuecomment-372005597>, or mute
the thread

**Comment by phildini** [comment]
Hi there! It looks like this PR might be dead, so we're closing it for now. Feel free to re-open it if you'd like to continue. 😄

**Pull request closed without merging**
