### PR TITLE
App params

### PR DESCRIPTION
**Pull request by mshammel**
Hi!

This is my first submission to beeware so I'm learning the process. Please let me know if I missing anything or do anything incorrectly.

Updated tests for app.py for greater coverage and fixed bugs in app.py with reading metadata.

This required adding src/core/test_app.dist-info/METADATA which is normally ignored by the .gitignore - if this should be handled differently please advise.

## PR Checklist:

- [ X ] All new features have been tested
- [ X ] All new features have been documented
- [ X ] I have read the **CONTRIBUTING.md** file
- [ X ] I will abide by the code of conduct

### CODE REVIEW

**Comment by mshammel** [comment]
I saw the pre-test check fails, so I'm closing this request. I'll fix the errors and re-submit.

**Comment by mshammel** [comment]
Re-opening, potentially just for discussion.

I believe the changes to app.py are straightforward.

But I have issues with my update to test_app.py. I have two CI checks failing. The first is easy code cleanup. The second is because I added a file not currently in the repo. In order for the additional testing I needed to supply a METADATA file. What is the proper procedure for adding a new file? And should I even be adding this file?

In hindsight, I should've submitted two separate PRs for these additions, which I can still do if the app.py changes are acceptable but we don't want to adopt the test_app.py updates.

Thanks,
Mark

**Comment by mshammel** [comment]
Hi,

Just checking to see if there is anything I should do with this PR.

Thanks,
Mark

**Comment by freakboy3742** [comment]
@mshammel I generally don't review PRs until they're passing CI; and I missed the notification that you'd asked a question about the specific test failure you were seeing. Apologies for dropping the ball on that.

I'm guessing the problem here is that check-manifest is comparing the files in git to the MANIFEST file; but the fact that the `dist-info` files are normally git-ignored is causing problems. It might also be because *MANIFEST.in* ignores distinfo files by default. I can't say I know a fix for this off the top of my head; if the file is needed to make the test pass, then that's the investigation you'll need to do.

I will say, however, that the location of the dist-info file concerns me. It's currently sitting in the base of the toga-core package, which isn't somewhere that a test artefact should be located. I'm also interested whether this set of tests will actually test the underlying problem - that different modes of execution cause different metadata injection (i.e., `python app.py` behaves differently to `python -m app`). I'm not sure I can see how you can effectively test that without actually invoking a sub interpreter as part of the test.

**Comment by mshammel** [comment]
Okay, I have confirmed that I can resolve the CI by updating MANIFEST.in files. The question is whether or not you want me to.

My understanding is that for any project as created by briefcase, the dist-info directory exists at the same level as the project directory. So for my personal project, I have:

```
myproject/
  __init__.py
  __main__.py
  …
myproject.dist-info/
  INSTALLER
  METADATA
```

So having the test_app.dist-info directory at the location I’ve placed it makes sense to me in this context, but I understand if that’s still not how you want to structure the tests. But it does work.

It’s possible I’m not explaining my goal here properly so let me back up a bit (and apologies if this is already all understood). In my personal project, I’ve created my own About dialog (prior to #1053 ). It is grabbing all the info to be displayed from the myproject.dist-info/METADATA file, since that’s all conveniently created by briefcase. In doing so, I detected two errors in src/core/toga/app.py relating to the reading of the Home-page and Summary metadata. I corrected those (included in this PR, but will need updating if #1053 is approved) but also wanted to update test_app.py to catch this and any other METADATA errors in the future.

To do that, I changed AppTests() in test_app.py to be a general class of testing methods, and created two TestCase classes to test the 2 different methods of injecting data into an App - by explicitly specifying it in the constructor (AppTestsExplicit()) and by letting App read the data from the METADATA (in AppTestsManifest(), which I'm now realizing is improperly named).

As noted earlier, this does result in more lines of app.py being tested (from 82% to 94%) and if the errors in app.py are not fixed, then ‘python setup.py test’ fails, thus catching the errors and showing that test dist-info/METADATA is being properly read. As additional confirmation, removing lines from dist-info/METADATA also results in errors because test_app now expects them. So this seems to be the appropriate location for the dist-info, but there could be additional functionality that I’m not aware of.

You may still not want the dist-info/METADATA file in the repo, in which case I would need to find an alternate method to have test_app test its METADATA code. I could have test_app.py create the file when run. Let me know if that’s preferable.

Thanks for your patience with all this!

**Comment by freakboy3742** [comment]
To be clear - I don't have a problem including distinfo files as part of the codebase. The issue is the *location* of those files. As currently placed, `test-app.distinfo` is being included in `src/core`, which makes it appear like it is a "core" part of Toga. It isn't - it's a test artefact, and as such, it should be included somewhere in a tests folder. If that requires a deeper directory structure, then so be it - but `src/core` is not an acceptable location for a test artefact to be stored.

I'm also not especially concerned about the number of lines described by coverage. Coverage is a notoriously ineffective measure of test adequacy; it's a better measure than nothing, but ultimately, you need to make sure you have *branch* coverage, not just line coverage. 

In this case, the branches that are interesting are all stimulated by something that is external to toga.App - the state of `sys.modules` when the app runs, and the way that interacts with metadata loading from `importlib`. `sys.modules` is populated in different ways depending on whether you invoke `python -m myapp` or `python myapp/app.py` or `python myapp.py`; and that will then be modified by whether the user has provided metadata arguments to the app, or they've got a distinfo file for the app. *That* is the behavior that we actually need to test here.

The only way to reliably test that is to *actually start an interpreter*. As such, a simple unit test that instantiates an instance of `toga.App()` *will not* be sufficient in this case. You're going to need to start a subprocess, and observe the output of that process.

**Comment by mshammel** [comment]
Got it. I understand why the current location of the dist-info is not acceptable. I'll try pushing the files in the tests directory down and level, move dist-info in tests, and see what needs to be done to keep the tests running correctly.

Regarding the tests themselves, I thought I was doing a simple extension to the existing tests, but clearly it's much deeper than that. But I'm happy to learn. I'll dig deeper into how `sys.modules` and `importlib` operate under the different invocations and study the existing test suite more thoroughly. I _think_ I know the direction you're heading, but if you have examples you'd like me to follow let me know.

Again, thanks for all the explanations and direction.

**Comment by freakboy3742** [comment]
Unfortunately, I can't point you at any good examples - this would be new ground for the Toga test suite; and the general complexity around managing this type of test is one of the reasons it doesn't already exist :-)

I *am* very motivated to improve the testing of this part of the codebase, though - so if there's anything I can do to help you in your journey, please let me know.

**Comment by mshammel** [comment]
Sounds good.

I think this PR has served its purpose and the investigation should be moved to a new issue. Do you want to create it with all your requirements? Otherwise, I can create one pulling what I think are the key points from from this thread.

Thanks.

**Comment by freakboy3742** [comment]
If you want, I'm happy to consider this as a two PR problem. The first is fixing the immediate problem that you've found with metadata tags (`Home-page` and `Summary`). Given that we don't have any way to test those automatically, but the code is clearly wrong, we shouldn't let the perfect be the enemy of the good - If you strip out the tests that are causing the problem here, I'll merge that simplified patch. The second PR is to add the tests that we need around this functionality (which will be a much larger body of work)

**Comment by freakboy3742** [comment]
I've been able to roll the behavior fix from this patch into #1064; so I can now close this PR in favour of a future PR that addresses the app testing problem.

**Pull request closed without merging**
