### PR TITLE
Enhancement the documentation description of startup toga app

### PR DESCRIPTION
**Pull request by MuhammadMouradG**
## Describe your changes in detail
This will fix the issue #1052, taking inspiration from #1071

## What problem does this change solve?
Some starting up method have consequences, this PR guide user with simple way to avoid him encountering them and guide him with the simple way to avoid it completely. 

## Related issues
This will solve #1052 and #1071 issues

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by MuhammadMouradG** [comment]
@freakboy3742 Could you please take a look at this PR?

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
I'm not clear what message you're trying communicate here. The phrasing is fairly vague, and won't really help anyone make a decision - *especially* during a tutorial, where the goal is "do exactly what we're telling you to do".

If there are "consequences", then we should document what those are - in a reference or topic guide, not a tutorial. If there are bugs in some of those use cases (and there may well be), then we should log (and fix) those bugs.

**Comment by MuhammadMouradG** [comment]
I checked the tutorial again and what I am trying to tell to the user is rather than run the file as a python `module` the correct way to start the `toga` application is by running it as a python `package`, specially, when your `toga` application including more than python script, for example your application uses some external icons. The advantage of doing that is that you telling `toga` where it is can find other submodules (icons folder in our case). Running python `package` requires creating some files and arranging it in specific hierarchic. What was my intent by this PR is guiding the user with an easy recommendation for run his `toga` application and it is "Use the Briefcase bootstrap". 

@freakboy3742 maybe, I failed to describe it perfectly in the PR, I am not an English native speaker, so I think, if you understand me, you can clarify that in the documentation.

**Comment by MuhammadMouradG** [comment]
Close this for inactive review status for long time and I don't able to maintaining this PR for long time.

If it is still interesting, please, let me know.

**Comment by SamSchott** [comment]
Apologies for the slow process. To chime in on this, I appreciate that there are currently gaps in the documentation, especially regarding the app structure. However, I agree with @freakboy3742 that the current changes are a bit confusing. Specifically:

1. You propose modifications to the "Running the app" section but your additions describe an app structure which is different from the structure described in the previous "Write the app" section.
2. A toga app can be written as either a single file module or a package with submodules. If you want to bundle resources such as custom icons with your app, a package structure makes more sense. Both are valid but different structures and I would prefer sticking to the single file structure for this tutorial because it is simpler.

I agree that it is probably worth introducing the package structure or linking to relevant documentation, especially since it is used in our own `examples` folder. Users which are new to Python might not be familiar with running a "package" as a module with the `-m` option. However, this may be better suited for a chapter in the How-to Guides where we have the space to discuss how to structure your app (`__main__.py`, `__init__.py`, `resources`, etc).

I also note that there is some overlap with the general BeeWare tutorial here which describes the app structure in some detail:

https://docs.beeware.org/en/latest/tutorial/tutorial-2.html#what-was-generated

**Comment by MuhammadMouradG** [comment]
Hi @SamSchott, thanks for your attention...

> 1. You propose modifications to the "Running the app" section but your additions describe an app structure which is different from the structure described in the previous "Write the app" section.

From my experience and as I believe the first method that beginners (in our case for `Toga` or `Python`) learn is the method that sticks in the mind no matter how complicated it is (if we suppose it is complicated), especially when this method is from a trusted person (in our case the official `Toga` documentation), also they think it works for all cases. What I am trying to say is that they will also use that method in trying the given examples, and I will leave you to imagine the impression they will have when they run the examples as they have learned (i.e. `python -m app`) and then find that some of the formal examples that are supposedly tested do not work as described (although the examples work fine but they run it in wrong way and unfortunately this is because this is the first thing that they are learned)... 

**As you might think**, I then suggest changing the structure of the tutorial, and we can discuss this later if you agree with what I am suggesting.

> 2. A toga app can be written as either a single file module or a package with submodules. If you want to bundle resources such as custom icons with your app, a package structure makes more sense.

I don't know why we mention this method (single file module) at all, later on most of the using cases of `Toga` will be include submodules at least for custom icons. Also, running the `taga` application as a package is not that complicated to be hard for beginners.

>  Both are valid but different structures and I would prefer sticking to the single file structure for this tutorial because it is simpler.

Run the app as a single file module may be simpler in describe and in give you first `hello world` example but most of the users who came here came to build their own app (which mostly contains submodules) and not to try the examples. In addition, the way they will learn in the tutorial will not help them if their application contains submodules.

> this may be better suited for a chapter in the How-to Guides where we have the space to discuss how to structure your app (__main__.py, __init__.py, resources, etc).

Your suggestion is good for me but I am just trying to share with you my thoughts about this problem and draw your attention to the problems that I think the newbie may encounter them.

**Comment by SamSchott** [comment]
@MuhammadMouradG, I certainly acknowledge that you and potentially others who are new to toga may be confused about the app structure. The discrepancy between the toga examples and the tutorial is certainly not ideal. However, I am wondering whether expanding the toga tutorial as you suggest will duplicate information which is already provided to some degree in the general BeeWare docs at https://docs.beeware.org/en/latest/tutorial/tutorial-2.html. It might make more sense to link to this documentation and recommend using `briefcase` to bootstrap a fully functioning app. If you find that the BeeWare tutorial is similarly confusing, please point us towards any issues that you see with it.

Personally, I would prefer a more in-depth guide about the app structure in the How-to section which explains different startup modes and their consequences (for example running as a module vs running as a file).

However, I haven't personally been involved in writing any of the docs. @freakboy3742 might have different opinions about how they should be structured and what the relationship between the BeeWare docs and the individual package docs should be.

**Pull request closed without merging**
