### PR TITLE
Pack layout system: fixing two bugs

### PR DESCRIPTION
**Pull request by shape-warrior-t**
This pull request aims to fix the two bugs in the layout code that I pointed out on Discord: alignment taking padding into account incorrectly, and left alignment and right alignment being switched from how they should be.

More work is likely needed regarding tests for this behaviour, so this pull request is not yet ready for review.

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by shape-warrior-t** [comment]
For reference, here are the examples that I shared on Discord of what things should look like under the fix:

fix demo - row
fix demo - column

These E-shaped structures illustrate how alignment should work when padding is involved, for each of the 3 * 2 types of alignment. We have a column/row of rows/columns. In order, the alignment for each row/column is: TOP/LEFT, CENTER, BOTTOM/RIGHT. Within each row/column, there are 4 smaller elements, all labelled with numbers that indicate the padding. The first number indicates the padding on the top/left side, and the second number indicates the padding on the bottom/right side.

You see all of the instances of column/row, top/left, and bottom/right? To make things less of a headache for me, I set things up so that you could switch between the two structures just by changing a single variable. I think it might be a good idea to turn these E structures into a test case, though I'll have to rewrite the code because
> in getting to this to work for both rows and columns I've committed several crimes against the Python programming language. 😛 

If anyone has any thoughts, I'm open to hearing them.

**Comment by shape-warrior-t** [comment]
I rewrote the E structures demo, and now it contains both E structures in one application as well as 86% fewer crimes against the Python language! It looks like this now:

rewritten

The smiley face labels are there because I made my local copy of Toga turn assign a label of ':)' to buttons with falsy labels. They wouldn't show up in a normal copy of Toga.

Here's the source code (as .txt, because GitHub doesn't support .py):
[app.txt](https://github.com/beeware/toga/files/9386198/app.txt)

**Comment by shape-warrior-t** [comment]
I've translated the E structures demo into a test case, so now this pull request is ready for review.

I have some concerns about how long and unwieldy the test case is -- it's around the same size as all the other test cases combined! But... in the end, it should still do its job. Do let me know, though, if a better way of constructing the test case is desired. I wrote a bunch of formatting code to produce the test nodes, and used a lot of copy + paste and regex to produce the expected layouts.

One thing I discovered while making and debugging the test case is that `available_width` and `available_height` do not scale based on dpi, but explicitly specified dimensions do. I'm not sure whether that's a bug or just some intentional behaviour that produced some confusing results for me this time.

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
The actual fixes to the Pack implementation look dead on - nice work hunting them down.

The test case that you've provided looks very comprehensive as well - the only comment I'd make is related to your observation that this one test is bigger than all the other tests combined. That's generally an indication that you've got more than one test - generally speaking, a test case should be validating exactly one thing, as atomically as possible.

In this case I'd guess there's *at least* 6 distinct tests (Top, Center, Bottom vertical alignment; Left, centre and right horizontal alignment), with an argument to be made for twice that number (those 6, with padding, and without).

The Low/normal/HiDPI variants are OK to collapse into a single test, as they're all tests for the same *behaviour* - those are just checking that the actual values come out as expected. However, if I could work out a good way to parameterise those tests, ideally those would be all be independent tests as well.

Outside of the larger test structure, the only thing I can see that  that might need to be verified is that if there are multiple children in a parent with alignment, then the padding between the children is preserved, but the children are all appropriately aligned. As is, you're verifying a the alignment of a single child in a parent, but not the multiple case.

**Comment by shape-warrior-t** [comment]
OK, I'll work on breaking the test into smaller pieces when I have time.

As of now, there are actually 24 cases that are being checked: 6 alignments * 4 cases of padding (no padding, padding on one side only, padding on the other side only, padding on both sides). Now that I think of it, we might need to test one configuration for padding for each of the 6 cases: some padding on one side, and an _unequal_ amount of padding on the other side. Or maybe 3 cases: equal padding on each side, more padding on one side, more padding on the other side? I'll take another look at the code later to figure out what makes the most sense.

Can I get some elaboration on your final paragraph, please? Are we talking about something like this?:
```
row_box(alignment: bottom, children: [
    column_box(children: [
        box(padding_top: 10, padding_bottom: 20),
        box(padding_top: 20, padding_bottom: 30)
    ])
])
```

**Comment by freakboy3742** [comment]
> As of now, there are actually 24 cases that are being checked: 6 alignments * 4 cases of padding (no padding, padding on one side only, padding on the other side only, padding on both sides). Now that I think of it, we might need to test one configuration for padding for each of the 6 cases: some padding on one side, and an _unequal_ amount of padding on the other side. Or maybe 3 cases: equal padding on each side, more padding on one side, more padding on the other side? I'll take another look at the code later to figure out what makes the most sense.

The specific *size* of the padding doesn't matter so much, as there's nothing particularly "qualitative" about the algorithm; however, the quantities should be different enough to ensure that the left padding is actually being used on the left.

For example, if you have a box with 10px padding on the left *and* right, there's no way to be certain that you haven't inadvertently swapped the interpretation of left and right padding. However, if you use left=10, right=20, you can verify that the right padding is being applied on the right side, and the left padding on the left. Once you've verified that case, you don't then need to verify that left=20, right=10 case *also* works, because you won't learn anything new from that. 

The only reason you might need to test a case like that is if there was some sort of "max(left, right)" check in place - in which case you're checking that the biggest value will be picked, no matter which side it is on - but that isn't happening here, so it's not required.
 
> Can I get some elaboration on your final paragraph, please? Are we talking about something like this?:
> 
> ```
> row_box(alignment: bottom, children: [
>     column_box(children: [
>         box(padding_top: 10, padding_bottom: 20),
>         box(padding_top: 20, padding_bottom: 30)
>     ])
> ])
> ```

That's the sort of thing I had in mind, yes - in this case, you're looking to confirm that there's actually 40 pixels of space between the two innermost boxes, as well as the padding on the bottom of the bottom innermost element. Given we have a history of getting padding wrong, it would be easy for us to only honour the padding on one element, or collapse the padding, or something else.

**Comment by shape-warrior-t** [comment]
Noted, thanks.

I think one test, along the following lines, for each of the 6 alignments will be enough:
```
row(height=H, alignment=center, children=[
    column(padding_top=A, padding_bottom=B, children=[
        box(width=W, height=I, padding_top=C, padding_bottom=D),
        box(width=W, height=J, padding_top=E, padding_bottom=F),
    ])
])
```
I don't think we need any separate tests for no padding, since we never check the truthiness of padding and none of the arithmetic would change due to padding being 0.

Though something tells me we're actually testing for two separate things here:
A. Padding and alignment work together properly (which is the thing that this pull request is fixing). This is covered by the `row(children=[column])` part of the proposed test.
B. Padding in the main axis of a box (horizontal padding in a row, vertical padding in a column) works correctly -- in a column with children with padding, the height of the box is (top padding + height + bottom padding) for the first child + (top padding + height + bottom padding) for the second child, and the content of the column is (empty space) + (first child) + (empty space) + (more empty space) + (second child) + (empty space), where the empty space is consistent with the specified padding. This is covered by the `column(children=[box, box])` part of the proposed test.

I'm saying this because this here:
```
row_box(alignment: bottom, children: [
    column_box(children: [
        box(padding_top: 10, padding_bottom: 20),
        box(padding_top: 20, padding_bottom: 30)
    ])
])
```
shouldn't actually be affected by my changes -- my changes only affect the case where the _direct_ child of the box with alignment (in this case, the direct child is the column box) has padding.

So maybe we should have 8 cases instead: 6 for testing property A, 2 for testing property B (one horizontal, one vertical)? Ultimately, I think it depends on whether there's any reason to think it's possible that properties A and B both hold in isolation and yet the example above works incorrectly. I don't see any such reason, but I'll defer to your judgement on this.

**Comment by freakboy3742** [comment]
> I don't think we need any separate tests for no padding, since we never check the truthiness of padding and none of the arithmetic would change due to padding being 0.

We don't do that *now*, but we should be treating testing as a black box where we don't know anything about the implementation. "No padding" is a reasonable case to test, and it's something that *could* easily get caught in a later change that introduces an "if padding" check.

> So maybe we should have 8 cases instead: 6 for testing property A, 2 for testing property B (one horizontal, one vertical)? Ultimately, I think it depends on whether there's any reason to think it's possible that properties A and B both hold in isolation and yet the example above works incorrectly. I don't see any such reason, but I'll defer to your judgement on this.

Generally, I'd argue that if there's any reason to suspect that there might be a problem case, either now or the future, and setting up the test case isn't prohibitively complex, it can't hurt to have another test.

**Comment by freakboy3742** [comment]
@shape-warrior-t That all seems reasonable to me!

**Comment by shape-warrior-t** [comment]
Update: The first 8 tests (main 6 + no padding) have been written.

I think I'm actually going to change the other 4 tests into 8 tests (6 of them relating to RTL mode):
- 2 tests to make sure row boxes within row boxes / column boxes within column boxes align correctly
- 2 tests to make sure children are laid out correctly in RTL row/column boxes with multiple children
- 4 tests to make sure alignment in RTL boxes (left, right, top, bottom) is in the correct direction.

I'll go ahead with writing those 8 tests whenever I can.

**Comment by shape-warrior-t** [comment]
Well, all of the test cases have been written...

Although, with 16 test cases and a minimum of 40 or so lines per test case, the code has become... a bit of a mess. I think it might be a good idea to find a different, less repetitive/boilerplatey way to test everything.

In particular, for these tests, I've designed everything so that:
- There's _a lot_ of repetition involved between test cases, many only differing in a few coordinates/dimensions.
- The final size and size of the main box will always be the same no matter what width and height are specified for `TestViewport`.
- Changing the DPI from 96 to 144 simply multiplies every single number in the layout by 3/2.

Is there anything we can do here? Just looking at the code is giving me a headache, and I'm sure nobody wants to read 600+ lines of code dedicated to testing just two things (interaction of alignment and padding, RTL stuff).

**Comment by shape-warrior-t** [comment]
...Hold on, didn't mean to delete a test case. Restoring it now...

**Review by freakboy3742 — APPROVED** [review]
I completely agree that this is eye-wateringly verbose, which is a problem because it's hard to reason whether a test is correct or not. 

However, I can't really say that I have much to offer by way of better options. If we move to pytest, parameterization is an option; that lets you cut down on some of the boilerplate, but I don't think it actually makes the tests any easier to reason about. 

Moving the test suite to pytest is on my TODO list for other reasons, so if you're particularly enthused, I wouldn't object to a pytest parameterised version of this test suite. I've marked this PR as approved; if you want to take a swing at a pytest-parameterised version of this suite, let me know; otherwise, I'll merge it as-is in all its verbose glory :-)

Fundamentally, I think the problem is that what we're evaluating here is a set of visual properties, and 20 lines of JSON is probably the worst possible way to quantify a visual property. Ironically, the screenshots in the PR comment are a more convincing proof of correctness than this 1000 line test suite - this test suite is more rigorous and repeatable, but a *lot* less readable.

There's a similar set of problems with GUI testing. Does the GTK backend render a Button correctly? When I render a 100px wide button with a blue background, do I get what I expect? We can test this by inspecting code properties, but that's complex and often brittle; fundamentally, the proof we're looking for is visual. What we need is a way to do visual tests - to render something as an image, and use *that* as the compliance case. I don't know what the answer is here, so if you've got any bright ideas, now would be a very good time... :-)

**Comment by shape-warrior-t** [comment]
All noted.

I don't have any experience with parameterizing tests via pytest (actually, I don't have much experience with pytest in general), and I couldn't get things working within, like, 5 minutes, so I think we can merge as-is for now. I can try to take a more involved look at things later.

I was more thinking of running a for-loop or something _within_ a test function, but in hindsight that's probably not a good way to do parameterization. I'd rather maybe poke around with pytest and see if I can revamp things at a later time.

**Comment by freakboy3742** [comment]
Awesome - merge as-is it is, then :-)

FWIW: The Briefcase codebase is all pytest, and it makes extensive use of parameterization, so if you're looking for a codebase to get up to speed, that's a good place to start.

**Comment by shape-warrior-t** [comment]
:)

I suppose I'll be checking out the Briefcase codebase, then!

**Comment by mhsmith** [comment]
If multiple tests contain common code which differs only in a few values, we should factor the identical parts out into a utility function which takes the differing parts as arguments. It's just as important to do this with test code as with production code, because as Russell said, if the test code is huge and repetitive, it becomes much harder to understand and to maintain.

The standard library `unittest` also has a ` subTest` context manager which allows you to add loops to tests within which a failure will only terminate the current loop iteration, not the whole test function. I find this more readable and flexible than pytest parametrization because it can be applied to any part of the function, or multiple parts, or nested. That way, the test data can appear right next to where it's used, instead of all being listed at the top in a decorator.

Unfortunately I don't think pytest has a direct equivalent of `subTest`, though I see there's a plugin for it.

**Pull request merged**
