### PR TITLE
Set the direction on the SplitContainer

### PR DESCRIPTION
**Pull request by GaretJax**

### CODE REVIEW

**Comment by BrendanSimon** [comment]
I was just about to push a pull request for the same fix.  Why is there a merge conflict?

Also, the argument `direction=True` that is generated is meaningless.

Either use `horizontal=False` (or `vertical=True`) - similar to `ScrollContainer`

or arguably even better, use an `Enum` for direction instead of `HORIZONTAL = False` and `VERTICAL = True`

**Comment by freakboy3742** [comment]
@BrendanSimon The merge conflict is because the patch was submitted some time ago, but the file that it is fixing has since changed. In this case, it appears the file has moved from it's original location.

**Comment by BrendanSimon** [comment]
Ok.  I can resubmit a new pull request.

Another alternative for the direction setting is:

```python
HORIZONTAL = 'horizontal'
VERTICAL = 'vertical'
```

**Comment by freakboy3742** [comment]
Closing in favour of #802.

**Pull request closed without merging**
