### PR TITLE
Update Travertino requirement

### PR DESCRIPTION
**Pull request by HalfWhitt**
~~Testing #2942 against updated Travertino.~~

Now that #2942 is merged, I've edited this to update the Travertino requirement to >= 0.3.0, < 0.4.0.

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by HalfWhitt** [comment]
https://github.com/beeware/toga/issues/2632 strikes again. Is macOS stalling out new? I don't know if I've seen that one before.

**Comment by freakboy3742** [comment]
> #2632 strikes again. Is macOS stalling out new? I don't know if I've seen that one before.

The macOS x86_64 failure does happen from time to time - it's often co-morbid with the Windows failure, suggesting some sort of network glitch.

**Comment by HalfWhitt** [comment]
And #2000 too! On a roll tonight.

**Comment by freakboy3742** [comment]
> And #2000 too! On a roll tonight.

Yeah... but at least it's a *different* failure... 🤣

**Comment by HalfWhitt** [comment]
My ambitious nature is not yet sated. One day I will have a PR that accomplishes *all* possible failures!

**Review by freakboy3742 — APPROVED** [review]
👍

**Pull request merged**
