### PR TITLE
Implemented Divider Widget on Android.

### PR DESCRIPTION
**Pull request by proneon267**
Implemented the Android Divider widget. Additionally, I've enabled the Android divider test in the testbed and verified that this PR successfully passes it. Here's the example divider app:

With the audits complete, I will now focus on creating tests for #1930. I'm submitting this PR to avoid any potential loss of progress. Please review it at your convenience, no rush! 😊

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by freakboy3742** [comment]
One quick observation: if you're adding a new widget, you also need to update the support matrix: https://github.com/beeware/toga/blob/main/docs/reference/data/widgets_by_platform.csv

**Comment by proneon267** [comment]
Done. Thanks!

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
Definitely does what it says :-)

The only question I have is whether TextView is the appropriate native widget for this. I know Android has a definite lean towards "every widget is a text input"... but it seems like overkill for a Divider which has *no* interactive component. In fact, the only thing this seems to be using the view for is rendering a 1px wide background. Could `android.view.View` be used instead?

**Comment by proneon267** [comment]
Done. Using View seems to be more appropriate. Thanks!

**Review by freakboy3742 — APPROVED** [review]
Looks good - thanks for the contribution!

**Pull request merged**
