### PR TITLE
Add slider methods

### PR DESCRIPTION
**Pull request by saroad2**
Added few abilities to `toga.Slider`:

1. When setting the `value` property of the slider, call the `on_slide` method`
2. Add increase/decrease by value methods, both safely and unsafely
3. Add increase/decrease by ticks methods, both safely and unsafely

Added the ability check in the slider example

## PR Checklist:

- [X] All new features have been tested
- [ ] All new features have been documented
- [X] I have read the **CONTRIBUTING.md** file
- [X] I will abide by the code of conduct

### CODE REVIEW

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
Mechanically, the logic around value changes, and the extensions to the example look good.

My hesitation is about the API. `increase_value()`/`increase_ticks()` definitely works; but we have an opportunity to do something a lot more pythonic without a whole lot more effort. If we convert `value` into a [descriptor](https://docs.python.org/3/howto/descriptor.html#descriptor-example), we would be able to do:

   myslider.value += 10
   
to increase the value by some delta. If we made `tick_value` a descriptor as well, we could also do:

    myslider.tick_value += 1

to increase the value by one tick. The end functionality is the same, but it feels a lot more Pythonic because you're using familiar operators, rather than needing to look up the names of mutator functions. Thoughts?

I'm also not completely convinced there's a good use case for the 'unsafe' mode you've described. I'd argue that value should simply be clipped (i.e, what you've set as the 'safe' default mode). I could even be convinced that safe behavior should be applied to normal value assignment as well... Do you have a specific use case for 'unsafe' increases, or is this a case of preserving the original `value` error handling behavior rather than a deliberate decision?

(This PR also makes me wonder if `on_slide` should be `on_change`... but that's a separate issue that doesn't necessarily have to be resolved here)

**Comment by saroad2** [comment]
If I understand you correctly, yo suggest adding the following class:

```python
class NumericProperty:

    def __init__(self, init_val, setter=None):
        self._val = init_val
        self._setter = setter

    def __get__(self, instance, owner):
        return self._val

    def __set__(self, instance, value):
        self._val = value
        if self._setter is not None:
            self._setter()

    def __iadd__(self, other):
        self.__set__(None, self._val + other)

    def __isub__(self, other):
        self.__set__(None, self._val - other)
```

And use it instead of `property`.
Am I correct?

**Comment by freakboy3742** [comment]
Yes - that's the sort of thing I had in mind. It's a little more code for us, but it means the end-users get an API that uses Python native operators, rather than needing to remember function names.

This is definitely a Toga thing, though - it's about manipulating the properties of widgets, rather than the style.

**Comment by saroad2** [comment]
Apparently, python's `property` supports `+=` and `-=`!

Therefore, only needed to implement the `tick_value` property which was missing.

Pay attention that now we lost the "safe" increment, but it's not that bad.

**Review by freakboy3742 — APPROVED** [review]
Looks good - and a nice catch on the `+=` handling!

I've made one small tweak; `tick_value` is a derived value, so it doesn't need to be independently maintained as a property on the widget. This also simplifies the event handler, as the "recompute" mechanism is no longer required. 

(As a side note - the recompute mechanism was actually broken; it didn't account for the case where *no* event handler was installed. However, it's a moot point since it's no longer required.)

I've also taken the opportunity to make the `on_slide`->`on_change` transition that I mentioned; I've done it in a backwards compatible way, introducing warnings if you use the old name.

**Pull request merged**
