### PR TITLE
Fix split container orientation and set the splitter position

### PR DESCRIPTION
**Pull request by MuhammadMouradG**
## Describe your changes in detail
This PR will use the weight of each split provided from the interface to set the position of splitter.

## PR Checklist:
- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
As with other recent PRs; a surface inspection of the code makes sense - but it's not clear what the testing strategy is for this code. Part of the process of reviewing and approving PRs is for me to verify that your fixes actually do what you claim. If you don't provide any details about your testing regiment, it can be difficult to do this testing. 

This test description could be:
 * Instructions for how to observe the before/after behavior in an existing example
 * Descriptions of a modification that can be made to an existing example to generate the behavior
 * The PR including a change to an example to demonstrate a relevant API.

**Comment by MuhammadMouradG** [comment]
When your fingers get dip in the mud, you think all people are like that and see what you are seeing :-), so I'm sorry for not making that clear.

For `Fix SplitContainer orientation` commit, as the documentation describe, we will pass to the `direction` argument object of `SplitContainer.HORIZONTAL` or `SplitContainer.VERTICAL` to determine the direction of `SplitContainer`. In fact, `SplitContainer.VERTICAL` == `True` and `SplitContainer.HORIZONTAL` == `False`. As you may note, the previous implementation does not set the `direction` to horizontal ever because it is `False`, so I changed the `if condition` to set the direction to vertical when `self.interface.direction` is `True` and to horizontal when `self.interface.direction` is `False`.

For `Update` commit, is only an initial thought of how I can implement the `weight` option.

For `Set the position of spliter using the split weights` commit, as the documentation describe, I should be able to set the position of splitter depending on my preferred weight of each split. The previous implementation does not have implementation to this option, so I implement this in `Gtk` and `Winform`.
### How to see the behavior before and after changes
Find and change these 2 lines of `tutorial2`, after that run your application, you will not see any change on the splitter position.
```python
split = toga.SplitContainer(style=Pack(width=500, height=500), direction=toga.SplitContainer.VERTICAL)
split.content = [(left_container, 3, False), (right_container, 6)]
```
After you make changes you will be able to see the position of splitter will change to give the left split 1/3 the space of window. The following is the result after changes:
Screenshot at 2020-10-11 04-35-42

Note, you will not be able to see this behavior if you are not pass this `style=Pack(width=500, height=500)` to `SplitContainer` because width and height will be 0 by default, if we be able to use width and height of the `app window` instead of `SplitContainer` this will be good.

**Comment by MuhammadMouradG** [comment]
@freakboy3742 Another enhancement that we may be able to implement is that when application window is resize the splitter will keep reserve the same weight of each split. If this feature is good, as I expect, please let me know and then I will update the implementation.

**Review by freakboy3742 — APPROVED** [review]
Thanks for the clarification - that makes a lot more sense now; and the extra bonus of the moving split is a nice addition, too!

**Pull request merged**
