### PR TITLE
Add `gap` style

### LINKED ISSUE #1943: Equivalent of CSS `gap` (padding between children)
If you want to add many children to a box with equal spacing between them, you have to add `padding` individually to every child, which is tedious. It would be useful to have something like the CSS [`gap`](https://developer.mozilla.org/en-US/docs/Web/CSS/gap) property, which is applied on the parent, and adds space between all of its children.

### PR DESCRIPTION
**Pull request by mhsmith**
* Fixes #1943

This PR is stacked on top of #3033, which should be merged first. To view only the relevant changes on the "Files changed" page, open the commits menu at the top left and use shift-click to select a range of commits.

I haven't updated all the examples that could benefit from this, but I've done one each with a row and a column layout.

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by HalfWhitt** [comment]
@mhsmith Some more commits over on #3033 now

**Comment by mhsmith** [comment]
`gap` would interact with potential future `column-gap` and `row-gap` properties in the same way as `margin` interacts with `margin_left`, etc.:

* You could set `gap` to an integer to set both gaps to the same value. This is the only option at the moment, because we only support 1-dimensional containers.
* Or set `gap` to a 2-tuple to set them to different values.
* Or set `column-gap` and `row-gap` individually.

**Comment by HalfWhitt** [comment]
> `gap` would interact with potential future `column_gap` and `row_gap` properties in the same way as `margin` interacts with `margin_left`, etc.:

Thank you for pointing this out... `directional_property`'s current implementation in Travertino would eventually need some generalizing to handle this.

**Review by freakboy3742 — APPROVED** [review]
👍 Looks exactly like what I'd expect.

**Pull request merged**
