### PR TITLE
Adding delay function

### LINKED ISSUE #1415: Delay or after function
**Is your feature request related to a problem? Please describe.**
I have been trying to make flashing text with Toga. I can make it using button, when you click the button text will disappear and when you click it again text will appear again. It looks like this:

    def startup(self):
        self.text_appearance = True

        def flash(widget):
            if self.text_appearance:
                main_box.remove(text)
                self.text_appearance = False
            else:
                main_box.add(text)
                self.text_appearance = True

        text = toga.Label("This text will disappear if you click the button")
        button = toga.Button("click me", on_press=flash)

        # Add components to the main box
        main_box = toga.Box(style=Pack(direction=COLUMN))
        main_box.add(button)
        main_box.add(text)

        # Show main window
        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()

But I am unable to find the function which will waits, for example, 2 seconds and then runs the flash function. Like the time.sleep(), Or to be more clear and get help from other GUI framework, like the after function from Tkinter.
The solution of my problem in Tkinter: https://stackoverflow.com/questions/27533244/how-to-make-a-flashing-text-box-in-tkinter

**Describe the solution you'd like**
To solve this problem, I would like to be able to do flashing without button, for example, something like this:

    def startup(self):
        self.text_appearance = True

        def flash(widget):
            if self.text_appearance:
                main_box.remove(text)
                self.text_appearance = False
            else:
                main_box.add(text)
                self.text_appearance = True
            self.main_window.after(2000, flash)

        text = toga.Label("This text is flashing")

        # Add components to the main box
        main_box = toga.Box(style=Pack(direction=COLUMN))
        main_box.add(text)

        # Show main window
        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()

        flash()

**Additional context**
Please inform me if there is a solution already. if not, please add this feature in Toga. I planed to do many things using this feature and I would love to see it.

### PR DESCRIPTION
**Pull request by VahilaK**
Add a function which facilitates to run a task after some time in background. 

This PR fixes #1415 

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
Thanks for the PR; while this does implement functionality that will run on a delay, it's not exactly what #1415 was requesting.

The original request was to install a background task, and that task included a 5 second delay.

This PR implements an asynchronous method that does a sleep as it's first step. 

The reason this matters is that you can only invoke your version of the method from an asynchronous context. This means it can't be invoked from a standard button handler, or from a generator.

**Comment by VahilaK** [comment]
@freakboy3742 I apologize for the delay in reverting. I understand there would be an issue with asynchronous context but I am not really sure on how to take this forward. One idea I have is to create a new thread which would add the method to background after the thread sleeps for the timeout duration. I am planning to use time.sleep in the new thread, this way there wouldn't be any asynchronous functions. Please let me know your views on this approach.

**Comment by freakboy3742** [comment]
> @freakboy3742 I apologize for the delay in reverting. I understand there would be an issue with asynchronous context but I am not really sure on how to take this forward. One idea I have is to create a new thread which would add the method to background after the thread sleeps for the timeout duration. I am planning to use time.sleep in the new thread, this way there wouldn't be any asynchronous functions. Please let me know your views on this approach.

There's no need to use threads - this can be done entirely with asyncio. However, you need to pay close attention to what it is that you're putting on the background task list.

Your implementation here is "sleep for 2 seconds and then call a function". What we need is "call a function right now whose first action is to sleep for 2 seconds".

**Comment by freakboy3742** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
