### PR TITLE
Widget gain and lose focus

### PR DESCRIPTION
**Pull request by saroad2**
Added the ability to run an action when a widget is gaining or losing focus.

Added an implementation in Windows and expanded the focus example app.

## PR Checklist:

- [X] All new features have been tested
- [X] All new features have been documented
- [X] I have read the **CONTRIBUTING.md** file
- [X] I will abide by the code of conduct

### CODE REVIEW

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
It definitely does what it says on the tin - but I have two comments; one cosmetic, one substantive.

The cosmetic one; from a naming perspective, I think I prefer "on_gain_focus" and "on_lose_focus" to "on_focus_gain" and "on_focus_loss". It's a really subtle active voice vs passive voice thing.

The substantive one: ...Why? What's the use case driving this? I can understand needing to track focus for a TextInput - you might want to clear the text field, or update the field in some way; but Button? Switch? While they do *technically* gain focus, that's a feature that is mostly an artefact of accessibility, rather than a core feature of the way a user interacts with the widgets.

**Comment by saroad2** [comment]
As for the naming, I changed the names to `on_gain_focus` and `on_lose_focus`.

As for the other thing, you are absolutely right. The reason I wanted this ability is for `toga.TextInput` (wanted to count how many times the user is focused on a text input). I moved the feature to be specifically in `toga.TextInput`. If one day we'll want to add this ability to other widgets, we'll move it back again.

**Review by freakboy3742 — APPROVED** [review]
Implementation looks good now; I've snuck in a couple of tweaks to the demo, and added a Cocoa implementation (can't have macOS lagging behind 😄 )

**Comment by saroad2** [comment]
Thanks for the merge!

Unfortunately, I don't have access anymore to a Mac computer, therefore I won't be able to implement both in Mac and Windows as i did before. So thank you for filling the gap!

**Pull request merged**
