### PR TITLE
Update test_activityindicator.py

### PR DESCRIPTION
**Pull request by Hassan-Mallah**
Setting and testing hide_when_stopped

## PR Checklist:

- [ ] All new features have been tested
- [ ] All new features have been documented
- [ ] I have read the **CONTRIBUTING.md** file
- [ ] I will abide by the code of conduct

### CODE REVIEW

**Comment by Hassan-Mallah** [comment]
Hey, 
Great feedback, thank you very much :)

I changed the value inside the test function, not setup.

for the last line is it correct?
or this option is better:
`self.assertEqual(self.activityindicator.hide_when_stopped, self.activityindicator.hide_when_stopped)`

Or maybe another way?

Cheers, Hassan

**Comment by Hassan-Mallah** [comment]
> Also - are there any other side effects? Does changing "hide when stopped" have any other side effects? What are those side effects? Can we test that those side effects have been performed?

I doubled check "activityindicator.py" i didnt find any direct changes. Maybe it's somewhere else which i didnt find :)

**Comment by freakboy3742** [comment]
for the last line is it correct?
> or this option is better:
> `self.assertEqual(self.activityindicator.hide_when_stopped, self.activityindicator.hide_when_stopped)`

My point is that it *can't* be one line. You need to check the value *at least* twice - get the initial value and check it, set it to something new, check the value has been changed. You need to be able to prove that the *behavior* of the method is correct, not just that every line of code has been executed. In this case, the behavior is "changing the value of hide_when_stopped" - which means you need to actually observe it change.

**Comment by Hassan-Mallah** [comment]
What about the current version?
i checked True and False
cheers

**Comment by Hassan-Mallah** [comment]
Thank you for your feedback, i'll do this one 1st :)

**Comment by Hassan-Mallah** [comment]
Hey again,

After spending some time with the code, I understand your point now :)
hide_when_stopped is connected to start and stop. which means we need to check more cases.

I need to check if the indicator is hidden or not as well, correct? I didn't manage to find visible or hidden status in ActivityIndicator.
After looking at other tests, there's Hidden test in test_pack.py 
Is it related to style?

After looking at other classes, almost none of them has public hidden/visble status as well (widget, Box, factory...)

Where should i look?

Cheers

**Comment by freakboy3742** [comment]
The connection to start and stop is not what I'm referring to - I'm referring to the connection to the implementation. Setting `hide_when_stopped` should hit an API on the implementation - so the test needs to verify *that* has happened.

Don't look specifically for "enable/disable" states - look for properties that have interactions with `_impl`.

**Comment by Hassan-Mallah** [comment]
It's me again :) 

I was very lucky with 1st PR, it was so smooth :smiley: 

for now i reached this part, checking default value and after changing it:
`

        self.assertTrue(self.activityindicator.hide_when_stopped)

        self.activityindicator.hide_when_stopped = False
        self.assertFalse(self.activityindicator.hide_when_stopped)`

I think i need to use assertActionPerformed, but there's no action connected to hide.
What do you think?

Thank you

**Comment by freakboy3742** [comment]
You're on the right track thinking that you need to use `assertActionPerformed` - but you're incorrect in saying there's no action. Look closer at the setter for `hide_when_stopped`. It does something.

**Comment by Hassan-Mallah** [comment]
Hey,

in _actions i found only 'Create, Start, Stop', but in _sets there are entries for hide_when_stopped.
the test is passed using assertValueSet, is this the right way?
` 

        self.assertTrue(self.activityindicator.hide_when_stopped)
        
        self.activityindicator.hide_when_stopped = False
        self.assertFalse(self.activityindicator.hide_when_stopped)

        self.assertValueSet(self.activityindicator, 'hide_when_stopped', False)`

Cheers

**Comment by freakboy3742** [comment]
That's the one! You're trying to validate that when the user uses the interface to modify hide_when_stopped, the underlying implementation is manipulated in some way.

Stick that into a test, and you'll be done!

**Comment by Hassan-Mallah** [comment]
Great way to start the day :)
Thank you

**Comment by Hassan-Mallah** [comment]
"macOS backend tests Failing" and i can't see the details to what cause the problem.
Any ideas?
thnks

**Comment by freakboy3742** [comment]
Looks like it's not you - Github appears to be having some problems at the moment. It looked like it might be a temporary problem, but I tried restarting and now it can't even check out the code. I'll keep an eye on this and try running the tests again in a few hours.

**Comment by Hassan-Mallah** [comment]
Thank you for the info. Hope it'll work out soon.
I'll work on something else then :)

Also, i dont see an option to redo the test, or do i need to change the file?
Cheers

**Pull request merged**
