### PR TITLE
Added ScrollContainer

### PR DESCRIPTION
**Pull request by leec1979**
This is still a WIP for issue #140. Running the tutorial now brings up the GUI but it isn't formatted correctly. Further work is still needed.

### CODE REVIEW

**Comment by freakboy3742** [comment]
This looks great so far - I've added a Work-In-Progress label; once you're ready for a full review and merge, let us know!

**Comment by clokep** [comment]
Cool! I'm going to close #140 since I'm not really working on it. @leec1979 What's the next step? Anything I can help you with?

**Comment by leec1979** [comment]
@clokep at this point I (or anyone who wants to help :)) need to debug why the tutorial GUI isn't displaying correctly. I haven't had any more time to dig into it and am tied up for the next week or two. I can get back to it after that if someone hasn't beat me to it.

**Comment by phildini** [comment]
Hi there! It looks like this PR might be dead, so we're closing it for now. Feel free to re-open it if you'd like to continue. 😄

**Pull request closed without merging**
