### PR TITLE
Fix for the incorrect scrolling of Table on Windows (Toga issue #1130)

### PR DESCRIPTION
**Pull request by t-arn**
This PR fixes issue #1130 (incorrect table display on scrolling on Windows)

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Review by freakboy3742 — APPROVED** [review]
👍 Awesome - works a treat! Thanks for digging into this!

**Comment by Gibsterrreee** [comment]
Hey Guys, 

newbie here, so I don't quite understand what I have to do with the checklist and the program thats been added here. Can someone explain what to do with the PR Checklist, etc? I am also experiencing similar problems with Tables on Toga.

Thank you for your help in advance!

**Comment by t-arn** [comment]
@Gibsterrreee This PR has recently been merged into the Toga master branch. This fix is not yet in the current (pre) distribution of Toga, though. If you want to use the fixed Table right away, you can do one of the following:
1. Pull the Toga master branch and reference it from your venv (using pip install -e)
2. Get the Table.py file from Github and copy it manually into your venv

**Comment by FlxVctr** [comment]
Thanks for this much needed fix. Can anyone say when it's to be released? (i.e. is it worth the effort to go with the cloning approach)

**Comment by freakboy3742** [comment]
@FlxVctr We're overdue for a Toga release, and there have been a bunch of improvements recently that are worth getting into a release; I'll add this to my todo list for today.

**Comment by freakboy3742** [comment]
@FlxVctr Confirmed: 0.3.0dev27 is now out, including this PR (and many others)

**Pull request merged**
