### PR TITLE
Async Cocoa dialogs

### PR DESCRIPTION
**Pull request by samschott**
This PR makes all Cocoa dialogs async and can be considered a followup to #987 for Android. Async dialogs on macOS are only possible when they are attached to a window as a sheet. This is not a problem for toga at the moment since it associates all dialogs with a window. Introducing application-wide dialogs will however be more difficult because the Cocoa API for this is _synchronous_.

This PR also cleans up the doc strings describing the dialog return types and introduces uniform return types for `select_folder` and `select_file`. Previously, `select_folder` would always return a list which could be empty (no folder selected), contain a single string (single file selected) or contain multiple strings (multiple folders selected). `select_folder` returns `None` (no file selected) a string (a single file selected) or a list of strings (multiple files selected). `open_file` similarly returns `None` or a string. For more uniform behaviour, `select_folder` has been adapted to follow the convention of the other dialogs.

Moving to async dialogs also fixes issue #1006.

This PR is marked as a draft because it requires awaiting the implementation methods in the interface layer. This will break other currently synchronous implementations.

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Review by freakboy3742 — COMMENTED** [review]
As a patch, this looks great. As you note, there's the an issue with the impl definition, but other than that, it looks great.

The question is about the implementation layer. From a purely technical perspective, it's trivial to convert dialogs to be asynchronous. My concern is whether that API is going to be confusing.

At present, async event handlers are entirely optional. As an end-developer, using async is entirely opt-in - and beginner programmers in particular don't need those headaches.
 
With the current API, a beginner programmer can write:

    def on _button_press(...):
        if my_app.question('Hey you', 'Do you like me?'):
            print("Yay, a new friend!")
        else:
            print("No worries, I still like you")

which is reasonably straightforward to explain, and doesn't involve any complex concepts. However, if we move to async, that button press handler *must* be async, and the if statement *must* be an await.

That's not too daunting to an experienced programmer; I'm just concerned it will be hard to explain to a  novice.

However, the status quo isn't viable, either. We've been able to make it work on macOS, GTK and Windows (with native APIs), and on iOS (with an event loop trick); but Android looks like it's going to break this API. So we need to do *something* different.

Some possible ideas:
 1. Proceed with making dialogs 100% async, and make beginners learn what that means 
 2. Provide all the blocking/question asking dialogs as async, but also provide a non-blocking (or not-guaranteed-blocking) "simple" dialog to "just display a message" in a synchronous fashion
 3. Provide sync *and* async dialogs; async remain as is, but the sync versions change into a 'callback' API - you provide the callback that you want to invoke when "OK" is pressed, and the callback you want when "CANCEL" is pressed, and so on. 
 4. Develop a blocking synchronous shim around the async APIs that beginners can use, but strongly suggest they upgrade
 5. Something else? I don't know if I'm missing any obvious options...

I'm really undecided on this, so any opinions or thoughts would be gratefully accepted.

**Comment by paulproteus** [comment]
> 1. Proceed with making dialogs 100% async, and make beginners learn what that means
> 2. Provide all the blocking/question asking dialogs as async, but also provide a non-blocking (or not-guaranteed-blocking) "simple" dialog to "just display a message" in a synchronous fashion
> 3. Provide sync _and_ async dialogs; async remain as is, but the sync versions change into a 'callback' API - you provide the callback that you want to invoke when "OK" is pressed, and the callback you want when "CANCEL" is pressed, and so on.
> 4. Develop a blocking synchronous shim around the async APIs that beginners can use, but strongly suggest they upgrade
> 5. Something else? I don't know if I'm missing any obvious options...

Another option is to declare that a dialog is a widget. In this case, it'd be configured with the usual Toga `on_press`-style handlers. (Presumably `on_accept` or `on_decline`, etc.) That would make things consistent. The more I consider this, the more I like it.

I took a quick look to find out if other UI libraries can provide context for us choosing. https://doc.qt.io/qt-5/qtwidgets-dialogs-classwizard-example.html seems to imply to me that Qt considers dialogs a widget; see also https://doc.qt.io/qt-5/qdialog.html . I don't know what other widget toolkits do.

Russell, I like your idea of not requiring newcomers to learn about `async`/`await`. 

If we don't make dialogs into widgets, then I am OK coming to terms with the idea that dialogs are advanced and require async/await. I'm personally unenthused about Toga having _two_ ways of configuring callbacks.

Just sharing opinions/thoughts; I'm not wedded to any particular approach here.

**Comment by SamSchott** [comment]
Hm, this is a difficult decision. Personally, I would favour having a single implementation of dialogs, whether they turn out to be widgets, synchronous or asynchronous methods. Having multiple options to achieve the same effect just seems confusing.

Regarding the options:

Async dialogs are the IMO the best way to handle dialogs. background tasks can continue while a dialog is shown and this is made explicit by the code, unlike the current hidden way of spinning the event loop during a dialog in macOS. The large downside really is that users will have to learn about async / await. Toga makes this easier by starting an event loop for you and allowing async callbacks. Still, this “magic” can be confusing because the Python documentation or stackoverflow tell a more complicated story.

The callback API would be consistent with the rest of Toga but will complicate the code flow significantly. Unlike typical widgets, dialogs disappear once the user has made a choice and the code flow continues afterwards. Of course, this is not universal: some dialogs remain on screen once clicked, because the provide a help button or to show the progress of a task which was started. Qt seems to handle this by providing a synchronous `exec` method which shows the dialog and returns the user’s choice once closed but also allows connecting to a `buttonClicked` signal to define a callback and showing the dialog like a regular window with `show`. The latter will be difficult with some native APIs and Qt circumvents them by generally drawing its own dialogs.

Personally, I am in favour of keeping dialogs as method but make them always async. Together with a good documentation and toga’s event loop integration, this should hopefully not be a large barrier to first time users.

Again, it’s a difficult choice. Maybe some more opinions, also from first time users, would be good before deciding.

**Comment by danyeaw** [comment]
I think it would help if we made an example of each option in Toga.

I think Tkinter, wxPython, and GTK provide a simple message dialog, and then there are more complex dialogs, including special ones for about dialogs, color choosers, and file choosers. The dialog aren't part of the Window, they are their own widget. I'm not saying we need to copy these APIs, but I think it provides a good place to start from.

## Tkinter Example:
```
import tkinter as tk
from tkinter import messagebox as mb


def info():
    mb.showinfo("Information", "This is an INFO MessageDialog")


tk.Button(text="Information", command=info).pack(fill=tk.X)
tk.mainloop()
```
## GTK Simple Dialog:
```
import gi

gi.require_version("Gtk", "3.0")
from gi.repository import Gtk


class MessageDialogWindow(Gtk.Window):
    def __init__(self):
        Gtk.Window.__init__(self, title="MessageDialog Example")

        box = Gtk.Box(spacing=6)
        self.add(box)

        button = Gtk.Button(label="Information")
        button.connect("clicked", self.on_info_clicked)
        box.add(button)

    def on_info_clicked(self, widget):
        dialog = Gtk.MessageDialog(
            transient_for=self,
            flags=0,
            message_type=Gtk.MessageType.INFO,
            buttons=Gtk.ButtonsType.OK,
            text="This is an INFO MessageDialog",
        )
        dialog.run()

        dialog.destroy()


win = MessageDialogWindow()
win.connect("destroy", Gtk.main_quit)
win.show_all()
Gtk.main()

```
## WX Example
```
import wx


def onButton(event):
    wx.MessageBox("This is an INFO MessageDialog", "Info", wx.OK | wx.ICON_INFORMATION)


app = wx.App()
frame = wx.Frame(None, -1, "MessageDialog Example")
frame.SetSize(0, 0, 150, 100)

panel = wx.Panel(frame, wx.ID_ANY)
button = wx.Button(panel, wx.ID_ANY, "Information", (10, 10))
button.Bind(wx.EVT_BUTTON, onButton)

frame.Show()
frame.Centre()
app.MainLoop()
```

**Comment by SamSchott** [comment]
@danyeaw, thanks for the overview. Are the methods to show the dialog in the example blocking, i.e., do they return once the dialog is dismissed, or non-blocking? And how does one retrieve the button pressed if the dialog provides a choice?

It seems to me that there are two choices which are to some degree independent of each other:

1. Do we make dialogs widgets or functions?
2. Should showing a dialog be async or sync?

Widgets might be better suited for "traditional" callbacks rather than sync or async show methods. Still, the Qt and the GTK example shows that there is a use case for synchronous methods (GTK's `dialog.run` sounds suspiciously like a synchronous method).

**Comment by freakboy3742** [comment]
Thanks for that @danyeaw. From some poking around the docs, it looks like GTK, WTX and Tk are all blocking on dialog display (or, they have a "show modal" option - AFAICT, your Wx example is non blocking, but Wx advises the use of `ShowModal()` for dialogs). Unfortunately, that's the behavior that is a problem, as Android (and iOS, if we remove the nasty hack) doesn't have a "modal" display mechanism. Even on platforms that *do* support modals (i.e., desktops), those modal methods can be problematic (see #1006).

The question is whether we:
 1. Try to find a hack that will give us modal dialogs on Android, and resolve issues with modals in an async context. In poking around, I found [this](https://stackoverflow.com/questions/6120567/android-how-to-get-a-modal-dialog-or-similar-modal-behavior), which might be a worth investigation; or
 2. Recognise that this is an inherently async activity, and require use of an async-compatible API approach; and if so, what API do we expose? 

My inclination is stop fighting the platform's desire to be async and go with option (2); the question is how to accomodate that in a way that won't scare off newcomers.

**Comment by paulproteus** [comment]
To answer the question about GTK dialogs being blocking or not: Quasi-no. From the [docs](https://developer.gnome.org/gtk3/stable/GtkDialog.html#gtk-dialog-run)

> gtk_dialog_run () [...] Blocks in a recursive main loop until the dialog either emits the “response” signal, or is destroyed. If the dialog is destroyed during the call to gtk_dialog_run(), gtk_dialog_run() returns GTK_RESPONSE_NONE. Otherwise, it returns the response ID from the ::response signal emission.
> [...]
> Note that even though the recursive main loop gives the effect of a modal dialog (it prevents the user from interacting with other windows in the same window group while the dialog is run), callbacks such as timeouts, IO channel watches, DND drops, etc, will be triggered during a gtk_dialog_run() call.

Not exactly sure how that works, but that's how I see it.

**Comment by freakboy3742** [comment]
@paulproteus "Blocking" probably isn't the right terminology here. What I was referring to was blocking at the "micro" level, rather than the app level. If I have code that says:

    response = show_dialog()
    more_processing(response)

will `show_dialog()` stop execution of the method until a response is available, and only proceed to `more_processing()` when a response is ready. That is "blocking" from the perspective of this particular method, but it needs to *not* be blocking from the perspective of the rest of the app, as other event handlers (ranging from redraws to background network processing) need to keep working. 

That's what GTK's docs are describing AFAICT (and it certainly matches the behaviour we see from using that method).

**Comment by danyeaw** [comment]
Is there a use case for both types of dialogs, one that stops other user interaction until a dialog selection is made and one that doesn't (just popping a notice up on the side)?

**Comment by freakboy3742** [comment]
@danyeaw Quite possibly - especially in the "info" case, where the only user response is acknowledgement. The only downside I can see to this is one of potential confusion - we wouldn't be able to guarantee that logic that came "after" the dialog was *guaranteed* to run after the dialog was dismissed. On many platforms (mostly desktop), it would; but on others (mostly mobile), it wouldn't.

**Comment by freakboy3742** [comment]
As a move to async dialogs is a change that needs to be done across all platforms at once, I'm going to merge it this PR into #1464.

**Pull request closed without merging**
