### PR TITLE
Add tab index

### LINKED ISSUE #1650: Control Widgets Tab Focus Order Via Code
Is your feature request related to a problem? Please describe.
========================================

*TL;DR - one should be able to control the tab focus order of widgets in a window.*

Assume you have a window with two buttons in a line named `button1` and `button2`.

If you insert `button3` between those two buttons, the tab order of the buttons will be the **order of insertion**, i.e. `button1`, `button2`, `button3`. You might want to change that order to be the **order of appearance on the screen**, i.e. `button1`, `button3`, `button2`.

This is a not bug, in my opinon. However, we would like to let our users have a way to control the tab order manually via code.

Describe the solution you'd like
====================
The way I see it, I can think of 3 possible APIs for that abbility:

Option I - `widget.next_tab` and `widget.prev_tab`
------------------------------------------------------
With this API, for each widget one should be able to define the next tab or prev tab. For example:
```python
widget1.next_tab = widget2
widget1.prev_tab = widget3
```

The problem with this approach is that it introduces a way in which one can jump between windows if we set the next tab of a widget to be a widget from another window. We can simply raise an exception if someone does that.

Option II - `widget.tab_index`
--------------------------------
another approach should be to set the tab index of a widget. In that way, the tab order will be selected for each window by the order of tab index. This is similar to the way the tab order is handled in [.Net](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.control.tabindex?view=windowsdesktop-6.0). For example:
```python
widget1.tab_index = 0
widget2.tab_index = 10
widget3.tab_index = 100
```

The problem with this approach that we have to keep track of the index of other widgets in order to decied which index to use for our widget.

Another problem happens in the case where we choose the tab index to be an index we already chose for another widget. We can solve this problem by bumping by 1 the index for every widget with our index or above.

Option III - `window.set_tab_index(widget, index)`
------------------------------------------------------
Another approach is to control the widgets order from the `window` class. In that way we can make sure that we do not set the index of a widget to be the same as another widget and we can make sure that we order the tab index of widgets which are only from our window.

The downside of this approach is that we cannot simply set the "next widget" or "previous widget" , we have to do this using the `window` instance.

Summary
============
I don't have a favorite approach, but I tend towards option II. We can also choose to implement more than one of those APIs.

I think this is an important feature and I can think of many use cases where one might need it.
Let me know what you think.

### PR DESCRIPTION
**Pull request by saroad2**
Fixes #1650

Now one can control the tab index order via code. In this PR I implemented it only for windows.

The decision for the API syntax is explained in the linked issue.

## PR Checklist:

- [X] All new features have been tested
- [X] All new features have been documented
- [X] I have read the **CONTRIBUTING.md** file
- [X] I will abide by the code of conduct

### CODE REVIEW

**Comment by mhsmith** [comment]
CodeCov just randomly fails sometimes. I tried it again now and it succeeded.

**Comment by mhsmith** [comment]
... except for a test failure related to this PR.

**Comment by saroad2** [comment]
@mhsmith , I fixed the problem, but again it seems to fail on things which are unrelated to the PR.

I don't know why

**Comment by mhsmith** [comment]
Intermittent network problems on CI are also something I've seen a few times over the last month.

**Review by freakboy3742 — APPROVED** [review]
I've made a small tweak to the release note, but otherwise, this looks good! 

(Now we just need it implemented everywhere else... 😄 )

**Comment by bruno-rino** [comment]
I'll take a swing at implementing this in cocoa, but first, a couple of questions:
- A more conceptual name for the `tab_index` property would be nicer, e.g. `focus_index`
- Since we're mirroring the winforms API, shouldn't we also include a `tab_stop` (or rather `focus_enabled`) property, to specify if the widget should be part of the focus chain?

**Comment by freakboy3742** [comment]
I agree that the `tab_index` naming isn't great; however, it's also the naming used in HTML for the same feature, which is the closest we get to a consensus on what the feature is called. 

That said, following Toga's general design principles, "tab" describes a very specific implementation of the behaviour with an action/key; "focus" is the more generic concept. On that basis, maybe "focus_index" would be a better name.

As for mirroring the API - see the design discussion on the original ticket.

**Pull request merged**
