### PR TITLE
Add font loading for GTK backend

### PR DESCRIPTION
**Pull request by freakboy3742**
Builds on the legwork done by @kiljoy001 and #1845; instead of vendoring the python-fontconfig library, and then using just 3 methods from it, this PR builds a ctypes binding for the 3 methods we need.

This design was [discussed in Discord](https://discord.com/channels/836455665257021440/836455665257021443/1091514710836387840) prior to python-fontconfig being considered, so there's no provenance/licensing issues.

With this PR, the `font` demo now works on Gtk.

I have also converted the core font tests to pytest, and got them to 100% coverage. This PR doesn't include a test probe for live tests.

Refs #1837.

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by freakboy3742** [comment]
My preference would still be to use GI bindings for fontconfig; however it appears that they're woefully inadequate at present, so we have to work with what we have.

**Comment by kiljoy001** [comment]
Looks good to me - fonts are loading.

**Review by kiljoy001 — APPROVED** [review]
Fonts load on my local system - thanks!

**Comment by freakboy3742** [comment]
I'm going to close this in favor of #1903 - the latter incorporates all of this PR, but also includes tests, so it's a much better candidate for merging.

**Pull request closed without merging**
