### PR TITLE
winforms impl of table column-width setting

### PR DESCRIPTION
**Pull request by teratorn**
Implement Table column-width setting for winforms

## PR Checklist:

- [ x] All new features have been tested
- [x ] All new features have been documented
- [x ] I have read the **CONTRIBUTING.md** file
- [x ] I will abide by the code of conduct

### CODE REVIEW

**Comment by SamSchott** [comment]
I think there is some overlap with #1085 which aims to introduce a new `Column` class that holds information about display properties (e.g., `min_width`, `max_width`) and determines how data is converted to views in the table column (e.g., checkboxes, icons, strings).

I didn't really have much time to work on it lately. Parts that are missing include:

* Windows implementation
* Callbacks to modify the data source from the GUI

If there is sufficient interest I can pick up the work on this again. Or if anyone else would like to pick it up, do get in touch!

**Comment by t-arn** [comment]
Your PR is just what I need, because the current winforms implementation is not good for much in a real application: Very often, we will have the situation that the colums are not wide enough and the user will have to manually adjust the width to see the complete values in the table. Really not sexy!

What do you think about adding following logic:
- when the value is > 1 then it is an amount of pixels (= your current implementation)
- when the value is >0 and <=1 then it is a percentage of the table width
- when the value is 0 the column should be as wide as the widest data or header value
- when the value is -1, the column takes up the rest of the table space. This value should then only be allowed once.

Besides, I think that when col_width is None or not specified, the default width of the colums should be the 0 from the above logic.

Best regards
Tom

**Comment by freakboy3742** [comment]
Thanks for the contribution. While this API change would definite solve an immediate short term problem, I'm more inclined to follow the general direction that is being pursued by #1085 - that API will give a much richer and more extensible interface for controlling the display of columns in a table, rather than the "magic interpretation of integers in a tuple" approach that this API would require.

**Comment by ericmangold** [comment]
Cool, no worries.

**Pull request closed without merging**
