### PR TITLE
tests: Add a test that a dialog is modal

### LINKED ISSUE #2446: Dialog windows are not modal
### Describe the bug

Create a dialog like this:
```
async def on_button_test(widget):
    await self.main_window.info_dialog(title="Dialog", message="An Info Dialog")
```
You can now click on the main window behind the dialog  and the main window is activated although the dialog is still floating above the window. This allows the dialog to be shown again or other actions to be triggered although the user should be blocked in the dialog.

Either change the behavior of dialogs to be modal or add a "modal={True|False}" property to "info_dialog" (and all similar functions) to enforce this.

### Steps to reproduce

1) Create self.main_window.info_dialog
2) Click main window
3) Main window is activated and can be interacted with. 

### Expected behavior

Main window can not be activated (dialog keeps focus)

### Screenshots

_No response_

### Environment

Linux (GenToo). Toga in virtual environment.

### Logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jepler**
In Gtk it's necessary to explicitly make dialog boxes modal. Do this & add a test.

This was also manually tested at PyConUS 2024 on Debian.

Closes #2446 

## PR Checklist:

- [x] All new features have been tested
- [ ] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by freakboy3742** [comment]
Thanks for the PR - the CI failure is because the PR is [missing a changenote]([https://toga.readthedocs.io/en/latest/how-to/contribute/code.html#add-change-information-for-release-notes)

**Comment by jepler** [comment]
Thanks, I've added a change note now.

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
Looks like there's a naming twist - it's `is_modal_dialog()` on the GTK backend and test, but `is_dialog_modal()` on all the other backends :-)

**Comment by jepler** [comment]
oops. which name do you prefer?

**Comment by freakboy3742** [comment]
Lets go with `is_modal_dialog`.

**Pull request merged**
