### PR TITLE
Support submenus in Windows + Mac

### PR DESCRIPTION
**Pull request by saroad2**
Added implementation of `toga.Command` submenus in Windows:

sub

My approach was to let `toga.Group` define a **parent group**, and use it in order to let *Toga* know that this group should be in a submenu of the other group. Also, added a `section` parameter to `toga.Group` that can be set only if the parent group is assigned.

## PR Checklist:

- [X] All new features have been tested
- [ ] All new features have been documented
- [X] I have read the **CONTRIBUTING.md** file
- [X] I will abide by the code of conduct

### CODE REVIEW

**Comment by saroad2** [comment]
closes #956

**Comment by saroad2** [comment]
Now also supported in Cocoa 😃 !

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
From an end-user API perspective, this looks great. Groups map really well to the submenu concept.

However, the underlying implementation seems a lot more complicated than it needs to be. I've flagged the MenuBuilder abstraction inline; unless I'm missing something, that extra class abstraction doesn't seem to add any functionality or clarity that wasn't already present (or could be easily added to) the single-method version. There's nothing recursive or stateful, and the MenuBuilder instance is discarded as soon as it's used. To me, that screams "this isn't an object". 

Related to this - the additions to Group seem a *lot* more complex than what is needed. Fundamentally, we need two things:
 * establish the order of insertion of menu items (because they'll appear in the menu in the order they are inserted)
 * establish the "parent" menu that the item is being added into. 

The tracking of parent/child relationships would be useful if we needed to navigate the menu hierarchy - but we don't. We only need to iterate over the commands in order - once - , create submenus as needed, and insert items, submenus, and separators on demand as we go. As long as we can establish a sort order for commands, we're set. 

The existing Group handling is based entirely on sorting a 4-tuple of `(group, section, order, label)`. If we convert that into a tuple-of-tuples structure that describes the "path" of the command, we get a data structure that is tuple-sortable, but returns the order that we need the commands to be iterated in. For example, the commands in Tutorial 2 generate sort keys of:

 * ((0, 0, "Things"), (0, 0, "Action 0"), )
 * ((0, 0, "Things"), (0, 0, "Action 1"), )
 * ((0, 0, "Things"), (0, 0, "Action 2"), )
 * ((0, 30, "Commands"), (0, 1, "Action 4"), )
 * ((0, 30, "Commands"), (0, 2, "Sub Menu"), (0, 1, "Action 6"),)
 * ((0, 30, "Commands"), (0, 2, "Sub Menu"), (0, 1, "Action 5"), )
 * ((0, 30, "Commands"), (0, 3, "Action 3"), )

Each inner tuple is `(section, order, label)`; in the outer tuple, the last element is the actual command; and all preceding elements describe the groups you'll traverse to find the menu item. In this example, there aren't any sections, so the first index is always 0. The Command menu gets the system order value of 30. Python sorts tuples by position; so even though Action 5 and 6 has more elements, they numerically sort before Action 3.

With this structure, and a relatively minor alteration to menu creation that allows for submenu creation on demand when first encountered, we'll get the menu ordering we need, and we don't need anything more complex than `__lt__` ordering and a sort key. Cyclic path detection also becomes relatively straightforward - a group can't occur twice in the "path" for a command.

Does that make sense?

Finally - in your implementation, the macOS menu is being created in the right order; however, the menu items aren't being correctly bound in my testing. Not sure if that's related to the MenuBuilder refactoring, or something else.

**Comment by saroad2** [comment]
Thanks for the review, Russell!

As for the `MenuBuilder` classes I've created, I still think those are necessary. The [Builder Design Pattern](https://en.wikipedia.org/wiki/Builder_pattern) is a quite known pattern designed specifically for those cases: when the creation of an object is complicated and requires some external logic. I think that the extraction of the logic into a separate class makes the code much easier to read. Moreover, in a future PR, I'll turn both builders into `toga.AppMenu` implementations that will allow us to add and remove commands dynamically. This is only my opinion on this matter and if you wish me to bring it back to the `App` classes, I would, but I really think this is the best way to do it.

As for the sorting of groups and subgroups, I haven't realized it's so easy to sort those things! Thanks for that.
However, I don't understand how the API should change. How do you want to specify that a group is a parent of another group? should I keep the `parent` parameter in the `toga.Group` constructor and remove the `children` parameter? Should I set the parenting relations inside the `toga.CommandsSet` class? what do you think is the right approach?

**Comment by freakboy3742** [comment]
Builder patterns are common in strong-OO languages like Java - but that doesn't mean they're good *Python*, and it doesn't mean they're appropriate here. 

Extensibility *might* be a reason to adopt that pattern here - however:

1. Once we've got the altered path-based sorting in place, there is maybe 5 lines of extra code needed to support submenus in the existing implementation.
2. I explicitly *don't* want to support dynamic menu changes. One thing that UX guides agree on is that menu items that magically appear and disappear is bad UX. If a menu option exists, it should always exist, and be disabled when it's not appropriate. Otherwise you end up with GUIs that aren't discoverable - because you can't browse the menu items to work out what *might* be possible.

As a result, I don't see that we actually gain anything from moving this piece of functionality into a separate class. The existing single function does everything we need, it's nicely self contained, and doesn't require persisting any state (other than the existence of actual menus).

As for the sorting API change - The current setup assumes every menu item can be described as `(group order, section number, order number, label)`, and menu items are sorted and constructed on that basis. I'm suggesting that changes to a tuple describing the "path" to the menu item, and each item on that path has an independent order.

The path for an existing one-level menu items would become: 

    ((group section, group order, group label), (item order, item section, item label))

Groups don't currently have a section - that's something we'd need to add. The path for a submenu would become:

    ((group section, group order, group label), (subgroup section, subgroup order, subgroup label), (item order, item section, item label))

This produces a single flat list of *all* commands, in the order they need to be created. As you iterate through that list, when the list of groups changes, you insert a new menu (or submenu) as appropriate; when the section changes, you introduce a separator in the current menu. This is almost identical to what happens now, except that the "new menu" check also needs to allow for a submenu to be added, and for the "current" menu to be restored when you reach the end of the the submenu items. The "current" menu will always be the one returned by looking up `path[-2]`.

**Comment by saroad2** [comment]
I agree with you about almost everything, except for the part about the dynamic commands. Here's a classic example (I know it's from Pycharm, but that just represents a greater example):

recent

When we want to have a "Recent" submenu, the commands should be added/removed dynamically after you load files:
1. Loading existing files from the list would move them to the top of the list
2. Adding new files will put them at the top of the list while removing the last one.

In order to make that happen, we need to add and remove commands dynamically. I know it adds the option of user to abuse this ability and make non-HIG applications, but I think we still should add this ability and let the user decided whether to use it or not, and in which manner to do so.

For example, I would like to this exact ability in *Eddington*, to have a list of the last recent files inserted.

About the other points, you've mentioned, I'll start fixing those now.

**Comment by freakboy3742** [comment]
I agree that "Recent files" definitely needs to exist, and it is "dynamic" in the sense that items in that submenu will appear and disappear. 

However, rather than opening a full dynamic menu API, I'd prefer to add a "data-source-backed command" - a subclass of the base command whose options are backed by a Toga source, who renders as a submenu, rather than an item. Each of the options on the submenu will have the same "action" (e.g., load file); the only difference is "which file is loaded". The command is effectively 'parameterised' by the submenu items. The user can add files to the source, and source notifications trigger when new menu items are inserted into the list (and when old items are dropped).

This could then be tied directly into document-based Apps as a default "open recent" option; users could define their own versions for "favourites" or other "dynamic, but parameterised" commands.

Does that makes sense?

**Comment by saroad2** [comment]
Fixed the PR based on code review.

Please let me know if I missed something.

**Review by freakboy3742 — APPROVED** [review]
This looks really solid - great work.

I've made a few small changes to simplify the looping structure in the Winforms implementation. I've also added some clarifying comments in the example, and made some small tweaks for debugging purposes to the `repr` implementation (including adding one for Break).

I've also added a GTK menu implementation, so we've got submenus across the board now!

**Pull request merged**
