### PR TITLE
Fixed Python version Requirement in Readme

### PR DESCRIPTION
**Pull request by HalfWhitt**
Noticed it still says 3.8. Is there anyway to set this to update dynamically? It's easy to miss.

## PR Checklist:

- [ ] All new features have been tested
- [ ] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Review by freakboy3742 — APPROVED** [review]
Bother. Nice catch. 

I'm not aware of any way to automate this, other than maintaining a manual list of places we know the Python version is referenced.

**Comment by rmartin16** [comment]
FWIW, I run something like `git grep 3\\.8` for things like this; a little coarse-grained but mostly effectively.

**Comment by freakboy3742** [comment]
> FWIW, I run something like `git grep 3\\.8` for things like this; a little coarse-grained but mostly effectively.

Yeah - I find that ends up catching lots of 3.8 references in .tox and .venv folders that are false positives - and there's enough of them that it ends up being unhelpful.

**Comment by rmartin16** [comment]
`git grep` respects `.gitignore` :)

**Comment by freakboy3742** [comment]
> `git grep` respects `.gitignore` :)

Oh - *git* grep... TIL :-)

**Comment by HalfWhitt** [comment]
I literally didn't realize that existed. TIL as well.

**Pull request merged**
