### PR TITLE
Add default validators

### PR DESCRIPTION
**Pull request by saroad2**
Added default validators in Toga and use them in the textinput example.

**Important Comment**
Because of the nature of the new feature, I implemented the tests in the [DDT](https://en.wikipedia.org/wiki/Data-driven_testing) methodology. Using the `unittest` package for DDT is not so great, but if one day we'll migrate the tests in Toga to `pytest` (as we did in Briefcase) we could use [pytest-cases ](https://smarie.github.io/python-pytest-cases/) which makes DDT tests much more readable.

## PR Checklist:

- [X] All new features have been tested
- [ ] All new features have been documented
- [X] I have read the **CONTRIBUTING.md** file
- [X] I will abide by the code of conduct

### CODE REVIEW

**Comment by saroad2** [comment]
Fixes #378

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
+1 to adding some default validators; and +1 to the extensive TDD here. The code that exists looks good generally (except for the double-underscore method names that I've flagged in the past).

My concern is mostly about high-level API. This didn't come up in the process of adding validators to TextInput (it probably should have - that's my oversight; although in my defence, actually seeing an API in use is often the best way to prove when an API has problems).

I see 2 problems. Firstly:

    TextInput(validators=validator.email())

`validator.email()` is a function invocation - when you look at that code, it suggests you're producing a result. However, the validation won't actually happen until the validation occurs.

To me, a validator is something that *will* be invoked, not something that has already been invoked. If the validator has state, or needs to be configured, then it should be a class, and that class should made be callable (by having a `__call__` method). Or, if it's a trivial validator that needs no configuration, it's a bare function, and you pass in the bare function.

    TextInput(validator=validator.email)
    TextInput(validator=validator.MinimumLength(10))

The second is the "combine" use case. Combining validators is such a fundamental need that I'm wondering if we shouldn't make that part of the core validation API by making the API:

    TextInput(validators=[
        validator.MinimumLength(10),
        validator.MaximumLength(100),
    ])

This removes the need for `validators.combine`.

A helpful side effect is that these two changes would align the API of Toga's validators with [Django's validators](https://docs.djangoproject.com/en/3.1/ref/validators/). That doesn't make the design inherently "correct"; but it does mean an axis of similarity that may aid onboarding for new users.

Thoughts?

**Comment by saroad2** [comment]
Fixed everything presented in the code review, except this:

> The second is the "combine" use case. Combining validators is such a fundamental need that I'm wondering if we shouldn't make that part of the core validation API by making the API:
> 
> ```
> TextInput(validators=[
>     validator.MinimumLength(10),
>     validator.MaximumLength(100),
> ])
> ```

Which I think should be addressed in a different PR.

**Review by freakboy3742 — APPROVED** [review]
👍 This looks good to me now. I'll submit a follow up shortly with the `combine` update.

**Pull request merged**
