### PR TITLE
Add 'ico', 'pdf', 'eps', and 'psd' to allowed extensions for Cocoa icons

### PR DESCRIPTION
**Pull request by SamSchott**
Have vector graphic file types deliberately been left out? PDF in particular is a common icon file type in macOS and recommended in Apple's human interface guidelines.

## PR Checklist:

- [x] All new features have been tested
- [ ] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by freakboy3742** [comment]
Can you provide a reference for this? I couldn't find any description of the allowed icon types in the [Apple macOS HIG](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/) other than "PNG" (and, apparently, "don't use ICNS"... )

**Comment by SamSchott** [comment]
A somewhat outdated overview of supported file types is given in Apple's [documentation archives](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Images/Images.html). The [new documentation](https://developer.apple.com/documentation/appkit/nsimage/1519988-imagetypes?language=objc) states that you can get supported file types with `NSImage.imageTypes()`. On macOS Catalina, this returns a long list which one could in principle query at runtime and convert to file extensions. For now, I thought it easier to add the most commonly used types. PDF is expressly recommended in the [HIG](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/custom-icons/).

Here is the output of `NSImage.imageTypes()` on Catalina:
```
    "com.adobe.pdf",
    "com.apple.pict",
    "com.adobe.encapsulated-postscript",
    "public.jpeg",
    "public.png",
    "com.compuserve.gif",
    "com.canon.tif-raw-image",
    "com.adobe.raw-image",
    "com.dxo.raw-image",
    "com.canon.cr2-raw-image",
    "com.canon.cr3-raw-image",
    "com.leafamerica.raw-image",
    "com.hasselblad.fff-raw-image",
    "com.hasselblad.3fr-raw-image",
    "com.nikon.raw-image",
    "com.nikon.nrw-raw-image",
    "com.pentax.raw-image",
    "com.samsung.raw-image",
    "com.sony.raw-image",
    "com.sony.sr2-raw-image",
    "com.sony.arw-raw-image",
    "com.epson.raw-image",
    "com.kodak.raw-image",
    "public.tiff",
    "public.jpeg-2000",
    "com.apple.atx",
    "org.khronos.astc",
    "org.khronos.ktx",
    "public.avci",
    "public.heic",
    "public.heics",
    "public.heif",
    "com.canon.crw-raw-image",
    "com.fuji.raw-image",
    "com.panasonic.raw-image",
    "com.panasonic.rw2-raw-image",
    "com.leica.raw-image",
    "com.leica.rwl-raw-image",
    "com.konicaminolta.raw-image",
    "com.olympus.sr-raw-image",
    "com.olympus.or-raw-image",
    "com.olympus.raw-image",
    "com.phaseone.raw-image",
    "com.microsoft.ico",
    "com.microsoft.bmp",
    "com.apple.icns",
    "com.adobe.photoshop-image",
    "com.microsoft.cur",
    "com.truevision.tga-image",
    "com.ilm.openexr-image",
    "com.sgi.sgi-image",
    "public.radiance",
    "public.pbm",
    "public.mpo-image",
    "public.pvr",
    "com.microsoft.dds"
```

**Comment by SamSchott** [comment]
I guess App icons are an exception, they should always be PNG. Otherwise, all formats allowed by NSImage are supported in principle while PDF and PNG are explicitly recommended. ICNS is used by some of Apple's own icons.

**Comment by SamSchott** [comment]
Fair point. And I agree, if we don't want to support formats that are superceded or not recommended for icons, it makes sense to also drop BMP and ICO.

It might be good to add the supported icon types per platform to the documentation, especially when they differ from what the native API allows.

**Pull request merged**
