### PR TITLE
Add code coverage to Toga

### PR DESCRIPTION
**Pull request by saroad2**
Add coverage tests to Toga core abilities. we are now on 91% coverage!

This PR is missing us to add **CODECOV_TOKEN** to the repository's secrets.

## PR Checklist:

- [X] All new features have been tested
- [ ] All new features have been documented
- [X] I have read the **CONTRIBUTING.md** file
- [X] I will abide by the code of conduct

### CODE REVIEW

**Review by freakboy3742 — APPROVED** [review]
Looks good to me (and I'm a little shocked that coverage is as high as 91%...)

**Comment by SamSchott** [comment]
@saroad2, this may be a stupid question but I thought I would ask here:

I can see that the coverage report is uploaded on every PR, even from non-maintainers. However, github secrets such as `secrets.CODECOV_TOKEN` should not be available to outside branches. How does this work? I am probably missing something really obvious.

**Comment by saroad2** [comment]
Let me start with the fact the CodeCov has a major bug with its coverage reports. I'm thinking about removing our integration with them and switch to something else.

As for the secret, it's available for Github Actions, not for the users. that's the reason it can run on every PR. the users themselves don't have access to the secret.

**Comment by SamSchott** [comment]
Not sure I understand. Couldn't the PR modify the Github Action itself to upload the secret to some server? From the [GitHub docs](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow):

> With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.

AFAIK, this includes PRs from forked repositories.

It looks like CodeCov might not actually use the secret at all during upload if the PR comes from an external fork: https://github.com/codecov/codecov-action/issues/29.

In any case, it seems to be working, apart issues with the coverage reports themselves...

**Pull request merged**
