### PR TITLE
evaluate_js implementation for winforms

### PR DESCRIPTION
**Pull request by Ksengine**
invokes script on document object of window.
is this async function correct?

## PR Checklist:

- [ ] All new features have been tested
- [ ] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
AFAICT this isn't correct. It might be correct for `invoke_javascript`, which is a method - but a method that has a simple return value, by defintion, can't be part of an async coroutine, as it requires blocking the event loop.

**Comment by Ksengine** [comment]
> AFAICT this isn't correct. It might be correct for `invoke_javascript`, which is a method - but a method that has a simple return value, by defintion, can't be part of an async coroutine, as it requires blocking the event loop.

How can I add support for asyncio.
.Net `invokeScript` is a sync function

**Comment by freakboy3742** [comment]
You either need to find a non-blocking method to execute Javascript, or develop a way to invoke it in a non-blocking fashion.

**Comment by Ksengine** [comment]
## solution one
use threading
**Problem - python threads are affected by GIL**
**Problem - cant use threads for webbrowser control as defined [here](https://stackoverflow.com/a/20505606/13416201)**

## solution two
we incject javascript(wrapped with non-blocking code). our wrap returns `None`-`null` immediately. but script is working.
after the job finished it passes the result to a python function.
**Problem - we had to add a little .net dll to call python methods from javascript.**

## solution three
we incject javascript(wrapped with non-blocking code). our wrap returns `None`-`null` immediately. but script is working.
after the job finished it changes the title of webpage by JSON string.
title changes handller can get it.
**Problem - is this wise?**

## solution four
we incject javascript(wrapped with non-blocking code). our wrap returns `None`-`null` immediately. but script is working.
after the job finished it sends results through an ajax request.
python server can collect results.
**Problem - we had to use a server(python built-in)**

whitch is the best way?
or have you an ides?

**Comment by freakboy3742** [comment]
Given that WebView has a a [WebView.InvokeStringAsync](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.invokescriptasync?view=winrt-19041#Windows_UI_Xaml_Controls_WebView_InvokeScriptAsync_System_String_Windows_Foundation_Collections_IIterable_System_String__) method, that would be my first suggestion.

I'd also be paying close attention to the possibility of a transition to using Edge/WebView2 - something that [you have identified as an option yourself](#1155). Given that WebView has been flagged as deprecated in Microsoft's own docs, I'd be wary of spending extensive time working on improvements to an API that will need to be reworked in the near future.

**Comment by Ksengine** [comment]
> Given that WebView has a a WebView.InvokeStringAsync method, that would be my first suggestion.

its only available for XAML(WPF) and EdgeHTML.

**Comment by Ksengine** [comment]
> ## solution one
> use threading
> **Problem - python threads are affected by GIL**
> **Problem - cant use threads for webbrowser control as defined [here](https://stackoverflow.com/a/20505606/13416201)**
> 
> ## solution two
> we incject javascript(wrapped with non-blocking code). our wrap returns `None`-`null` immediately. but script is working.
> after the job finished it passes the result to a python function.
> **Problem - we had to add a little .net dll to call python methods from javascript.**
> 
> ## solution three
> we incject javascript(wrapped with non-blocking code). our wrap returns `None`-`null` immediately. but script is working.
> after the job finished it changes the title of webpage by JSON string.
> title changes handller can get it.
> **Problem - is this wise?**
> 
> ## solution four
> we incject javascript(wrapped with non-blocking code). our wrap returns `None`-`null` immediately. but script is working.
> after the job finished it sends results through an ajax request.
> python server can collect results.
> **Problem - we had to use a server(python built-in)**
> 
> whitch is the best way?
> or have you an ides?

?

**Comment by freakboy3742** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
