### PR TITLE
[Android] Add support for multiple activities (multiple windows)

### PR DESCRIPTION
**Pull request by Hagb**
With Java part: https://github.com/beeware/briefcase-android-gradle-template/pull/41

What have been done:

- A listener object (`window.TogaWin`) is now for a window but not for the whole application -- codes about window in `app.App` and `app.TogaApp` are moved to `window.Window` and `window.TogaWin`; (The most of modification in this pr is refactor.)
- Use intent to create new window, with the id of the listener object (`window.TogaWin`) passed so that java part can get the listener of the new window.
- Dialogs are correctly attach to the window;
- A hack to defer the execution of methods of widgets (`Widget`), because these method need to access the activity of the window, which can't be got util we attach the widgets to a window and run `show()`;
- Implement `setText` method and `on_close` event

## Examples

<details>
  <summary><mark>Example 1 (creates multiple new windows dynamiclly, and shows the dialogs above a specific window)</mark></summary>

https://user-images.githubusercontent.com/10961094/147294412-6ee471db-b0ee-4b79-9ed2-3b45a42a62e1.mp4

```python
"""
Multi-windows test
"""
import toga
from toga.style import Pack
from toga.style.pack import COLUMN, ROW


class multiwintest(toga.App):

    def create_window(self, _):
        def on_close(_):
            self.n -= 1

        self.n += 1
        new_window = toga.Window(
            title=f"New window {self.n}", on_close=on_close)

        label1 = toga.Label("Use return key or close button to close this window")
        label2 = toga.Label(f"This is new window {self.n}")

        new_button = toga.Button("Create window", on_press=self.create_window)
        close_button = toga.Button("Close this window", on_press=lambda _: new_window.close())
        how_many_button = toga.Button(f"How many new windows? (It should be {self.n})",
                                      on_press=lambda _: new_window.info_dialog("Number of new windows", str(self.n)))

        box = toga.Box(style=Pack(direction=COLUMN))
        box.add(label1, label2, new_button, close_button, how_many_button)
        new_window.content = box
        self.windows.add(new_window)
        new_window.show()

    def startup(self):
        self.main_window = toga.MainWindow(title=self.formal_name)
        new_button = toga.Button("Create window", on_press=self.create_window)
        close_button = toga.Button(
            "Exit application", on_press=lambda _: self.main_window.close())
        how_many_button = toga.Button("How many new windows? (It should be 0)",
                                      on_press=lambda _: self.main_window.info_dialog("Number of new windows", str(self.n)))

        main_box = toga.Box(style=Pack(direction=COLUMN))
        main_box.add(new_button, close_button, how_many_button)
        self.n = 0 # It is the number of new windows
        self.main_window.content = main_box
        self.main_window.show()


def main():
    return multiwintest()

```
</details>

<details>
  <summary><mark>Example 2 (shows that the content of the window covered by the new window will be kept)</mark></summary>

The content of the window covered by the new window will not change. (Even the pointer in TextInput.)

https://user-images.githubusercontent.com/10961094/147417010-85003fc5-64cd-460e-94b3-3c8e28a90240.mp4

```python
import toga
from toga.style import Pack
from toga.style.pack import COLUMN, ROW


class multiwintest(toga.App):
    def new_window(self, _):
        window = toga.Window(title="New window with just a label")
        label = toga.Label("A label")
        window.content = label
        self.windows.add(window)
        window.show()

    def startup(self):
        self.main_window = toga.MainWindow(title=self.formal_name)
        label = toga.Label("Multi-windows test")
        input_ = toga.TextInput()
        button = toga.Button("New window", on_press=self.new_window)
        main_box = toga.Box(style=Pack(direction=COLUMN), children=(label, input_, button))
        self.main_window.content = main_box
        self.main_window.show()


def main():
    return multiwintest()
```

</details>

<details>
  <summary><mark>Example 3 (a more realistic example that simulates the process of login, has 3 different windows with different widgets, and shows that content in the windows covered by new window will not change when the new windows are closed)</mark></summary>
Assume a scenario about login

https://user-images.githubusercontent.com/10961094/147415993-eb276e19-6a7d-4ea3-a568-3d424a4a6708.mp4

```python
"""
Multi-windows test
"""
import toga
from toga.style import Pack
from toga.style.pack import COLUMN, ROW


class multiwintest(toga.App):
    def sign_in(self, _):
        login_win = LoginWindow(self)
        self.windows.add(login_win)
        login_win.show()

    def startup(self):
        self.main_window = toga.MainWindow(title=self.formal_name)
        self.user_label = toga.Label("Haven't logined")
        login_button = toga.Button("Sign in", on_press=self.sign_in)
        main_box = toga.Box(style=Pack(direction=COLUMN))
        main_box.add(self.user_label)
        main_box.add(login_button)
        self.main_window.content = main_box
        self.main_window.show()


class LoginWindow(toga.Window):
    def login(self, _):
        captcha_win = create_captcha_window(self)
        self.app_.windows.add(captcha_win)
        captcha_win.show()

    def __init__(self, app_):
        def on_close(_):
            self.app_.main_window.info_dialog(
                "Login status", self.login_status)
            self.app_.user_label.text = self.login_status

        super().__init__(on_close=on_close)
        self.login_status = "Haven't logined!"
        self.id_input = toga.TextInput(initial="user1")
        self.passwd_input = toga.PasswordInput(initial="passwd")
        login_button = toga.Button("Login (just pretend)", on_press=self.login)
        box = toga.Box(style=Pack(direction=COLUMN))
        box.add(self.id_input, self.passwd_input, login_button)
        self.content = box
        self.title = "Login Windows"
        self.app_ = app_


def create_captcha_window(login_win):
    win = toga.Window(title="Captcha Window")
    captcha_view = toga.ImageView(
        toga.Image("PATH TO AN IMAGE FILE.jpg"),
        style=Pack(height=login_win.app_.main_window.size[1]/2,
                   width=login_win.app_.main_window.size[0]*3/4))
    captcha_input = toga.TextInput()

    def on_press(_):
        if captcha_input.value:
            login_win.login_status = f"Login successfully, {login_win.id_input.value}!"
            win.close()
            login_win.close()
        else:
            win.info_dialog("Captcha needed", "Please input captcha")

    ok_button = toga.Button("OK", on_press=on_press)
    box = toga.Box(style=Pack(direction=COLUMN))
    box.add(captcha_view, captcha_input, ok_button)
    win.content = box
    return win


def main():
    return multiwintest()
```
</details>

## PR Checklist:

- [ ] All new features have been tested
- [ ] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by t-arn** [comment]
This is a very interesting PR, indeed! It makes writing cross platform, multi screen apps a lot easier and more consistent.

In a native Android app, every GUI page usually resides in its own Activity. 

Let's assume the following scenario: The user goes from the main screen to sub screen 1 and enters some data there. Then, he goes to sub screen 2 and then leaves sub screen 2 again (e.g. with the Android back button). In a normal native Android app, he will automatically be back in sub screen 1 where the before entered data is still there.

Does this work with your implementation where you actually have the same Activity (WinActivity) for all your sub screens?

In your example, you don't really have different sub screens. You always create the same sub screen again. Could you provide a more realistic example that shows the above scenario?

**Comment by Hagb** [comment]
@t-arn 
> Does this work with your implementation where you actually have the same Activity (WinActivity) for all your sub screens?

No. Different activities (windows) have different instances of WinActivity. Their classes are all the same WinActivity indeed (except that class of the main activity is the subclass of WinActivity).

> In your example, you don't really have different sub screens. You always create the same sub screen again. Could you provide a more realistic example that shows the above scenario?

I just edited the PR comment to add the example 2, which assumes a scenario about login.

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
@Hagb Thanks for this patch - it's very comprehensive; and from what I can tell, it does what it does really well.

My concern is over how the native Android concepts map to the Toga equivalents. Specifically, I'm not completely convinced that the mapping of `android.Activity` to `toga.Window` is correct. There's clearly *a* mapping required - but I don't think it's *Window*.

A "Window" in Toga is a self-contained piece of operating system chrome. On a desktop, this metaphor is obvious; but on a mobile app, this doesn't really make sense, so we've made the conceit that "a mobile app has exactly one window". This *might* be expanded in future to deal with external displays (consider a slide presentation app where the tablet has speaker notes, but the external display shows the slides - the "external display" might be a secondary window in that situation).

Android obviously requires an intermediate object to contain "pages" of content that can be used for navigation purposes, but I don't think a direct mapping to "window" is the right translation. The closest analog I can think of immediately would be "container" (which is a top-level collection of content - but that's not currently exposed as a first class object anywhere in toga. I suspect this needs to happen in the context of a more comprehensive design discussion around in-app navigation, and how some of the more complex widgets (like SplitContainer) should be interpreted on mobile platforms.

**Comment by Hagb** [comment]
@freakboy3742 Hi, thanks for review.

As far as I can see, `Activity` of Android doesn't behave completely like any object in current toga, and I even don't know whether there is a regular thing in desktop GUI like the this.

## Comparison with window

Same: By default, developers can open new activities/windows with new content, and users can close the activities/window by a button (`close` button in desktop) or key (`back` key in android).

Difference: Users can't freely switch between different activities of an app, and Android show only one activite in a screen (except for [split-screen and picture-in-picture](https://developer.android.com/guide/topics/large-screens/multi-window-support))

## Comparsion with container

If image an container which contents are activities of Android, we get such a container:

- By default this container behaves like a "stack" of `content`s (activities): it shows only the top `content`; when an activite is opened, a `content` is pushed; when an activite is closed, a `content` is popped. Not only that, there is a "standard operation" for user to close a activite, which is `back` key if in in Android, just like the `close` button in desktop.
- The range of such a container must be the _whole_ window, and by default when the "stack" becomes empty, the window will be closed. It is very different with a regular widget.

**Comment by freakboy3742** [comment]
@Hagb You're completely correct that Activity is a completely different type of object - Toga doesn't have anything similar, and I can't think of any other GUI API that has a comparable feature. 

The fact that you can't switch arbitrarily between Activities is the strongest example demonstrating why Activity != Window. 

Container looks like a much closer match - but I think my concept of Container is a little different to yours. It sounds like you're thinking of a Container as something that is inherently a stack of content; I'd suggest that a stack is just one way that content could be ordered (albeit a very common one).

My concept of Container is more like "widget with special privileges". It would simplify a lot of internal logic to be able to say "A window has content, which must be a Container", and then have different types of container that can themselves hold other containers (e.g., a SplitContainer holds 2+ child containers). This would also allow us to add a NavigationContainer which would manage "stack" style navigation; but the decision to use that sort of container would be optional. 

The "default" behavior would be a container that is "just there", much like the current behaviour of window - it doesn't support stacking additional panels of content; it's a single window with a single container that holds a collection of widgets. To get "stack" behavior, you'd need to explicitly use a Container that has "stack-like" behavior. 

Does that makes sense?

The only question that I have about this is how to manage complex container interactions. For example, Toga already has an OptionContainer. If we also had a NavigationContainer, we will have a situation where there are two different ways to construct an app - an OptionContainer that contains a NavigationContainer, and a NavigationContainer that contains an OptionContainer. These two aren't equivalent, though - in the former, the option tabs would be visible as you navigate deeper; in the latter, as you drill into the stack, the option tabs would disappear. We already have an OptionContainer for Android, which would allow the second implementation; how would we render the former? Is that app design even possible?

**Comment by freakboy3742** [comment]
Closing as I'm not convinced this specific PR is headed in the right direction; there's definitely something that needs to be developed here, but a more thorough design discussion is required.

**Pull request closed without merging**
