### PR TITLE
Fix text alignment for MultilineTextInput on Android

### PR DESCRIPTION
**Pull request by t-arn**
This PR fixes the issue https://github.com/beeware/toga/issues/1807 by removing following code in the `set_alignment` method of the Android implementation:
```
        # Refuse to set alignment unless widget has been added to a container.
        # This is because Android EditText requires LayoutParams before
        # setGravity() can be called.
        if not self.native.getLayoutParams():
            return
```
Although the remark claims that this save guard is needed, I cannot find any problem when removing it.

## PR Checklist:

- [x] All new features have been tested
- [ ] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by t-arn** [comment]
@mhsmith Please review this PR

**Comment by mhsmith** [comment]
Thanks, I'll have a look at this. The code in question was actually added by you in #1591. Did you notice any need for it at that time, or were you only copying it from textinput.py?

The code in textinput.py was added by @paulproteus in #1005, but a lot has changed since then.

**Comment by t-arn** [comment]
Yes, I also saw that I am to blame for this code. I actually did copy it from textinput. In my own dev branch I fixed it long ago and I never had problems since.

**Review by freakboy3742 — APPROVED** [review]
Definitely seems to work in my testing too; I think there's been a few tweaks to the way layouts happen that have made this particular piece of protection code unnecessary.

**Comment by mhsmith** [comment]
#1938 removes this code from the `set_alignment` methods of all other widgets. However, similar code still remains in the `rehint` methods, which may be unnecessary.

**Pull request merged**
