### PR TITLE
Fix scroll container min size

### PR DESCRIPTION
**Pull request by MuhammadMouradG**
## Describe your changes in detail
This PR aims to set minimum height and width of scroll content that reserves space to scrollbars.
## What problem does this change solve?
This PR will solve the issue described [here](https://gitlab.gnome.org/GNOME/gtk/-/issues/210)

## PR Checklist:
- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
This seems like a reasonable change; however, it's not clear to me that the change is actually doing anything. I can't see any change in behavior in the scrollcontainer example; is there another example that demonstrates that this change is actually fixing a problem?

**Comment by MuhammadMouradG** [comment]
The issue appear when the window size be smaller than scrollbars, the following is a screen record:
vokoscreenNG-2020-10-10-05-36-54

After set the minimum width the issue will be fix as describe in the previous link. The following is a screen record:
vokoscreenNG-2020-10-10-05-42-37

**Comment by freakboy3742** [comment]
Are you able to see that behavior on the normal tutorial2? Tutorial2 sets `horizontal=False` on the right hand size ScrollContainer, so the widget should *not* ever show a horizontal scrollbar. I wasn't able to get the behaviour you show without modifying the demo code to remove that option. If you *are* able to get a horizontal scrollbar without modifying the demo, then we have an interesting bug on our hands.

Also: Is there anything special about the 70px magic number? If not, it would be preferable to use `self.interface.MIN_WIDTH` and `self.interface.MIN_HEIGHT` for consistency with other platforms.

**Comment by MuhammadMouradG** [comment]
I modified the demo also to the `horizontal=True` to be able to see this problem.

The `70px` for two reasons, the first is that the minimum width of scrollbar is 55, and I added `15px` to give the user a good UX as these 15 give space for the slider to move when the window content moves, and this is the second reason.

**Review by freakboy3742 — APPROVED** [review]
Thanks for the clarification. Given that GTK doesn't provide a ready-to-use "minimum size" constant, I feel it is better to use a Toga-defined one. In this case, it's a little larger than what would be the "True" minimum size, but I don't think the extra 30 pixels will impact on anything in practice.

**Pull request merged**
