### PR TITLE
Fix handler function

### LINKED ISSUE #1098: Clarifying the `_handler` function formal parameter
This may be seem a bug. In line 49 of file `src/core/toga/handlers.py` in `_handler` function definition, in what the formal parameter `widget` is used? I can not find any object pass this parameter to itself? Could you please clarify the using?

This is the function definition:
```python
def _handler(widget, *args, **kwargs):
            if asyncio.iscoroutinefunction(handler):
                asyncio.ensure_future(
                    handler_with_cleanup(handler, cleanup, interface, *args, **kwargs)
                )
            else:
                result = handler(interface, *args, **kwargs)
                if inspect.isgenerator(result):
                    asyncio.ensure_future(
                        long_running_task(result, cleanup)
                    )
                else:
                    try:
                        if cleanup:
                            cleanup()
                        return result
                    except Exception as e:
                        print('Error in handler:', e, file=sys.stderr)
                        traceback.print_exc()
```

### PR DESCRIPTION
**Pull request by MuhammadMouradG**
## Describe your changes in detail
This PR removes unused formal parameter `widget` from `_handler` function definition and reuses it to bound `interface` argument, coming from outer scope and used in the `_handler` function scope, as a keyword argument.

Also, we discussed these changes in more details in #1098 issue and #1119 PR.

## What problem does this change solve?
The previous implementation of `_handler` function was not use `widget` parameter.

## Related issues
This pull request fix #1098 issue.

## PR Checklist:
- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by MuhammadMouradG** [comment]
@freakboy3742 Is this PR still interesting?

**Comment by MuhammadMouradG** [comment]
@freakboy3742 I think this PR needs to review.

**Comment by MuhammadMouradG** [comment]
@freakboy3742, The conflict has been resolved and the description of PR has been re-clarified. Take a look at this PR.

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
So... this doesn't break anything... but it's not complete.

The giveaway is the `widget=interface` argument on L60 on `wrapped_handler`. There shouldn't be any need for that argument - the whole purpose of `wrapped_handler()` is to build a closure of the widget over the handler method. If we're building a closure, we don't need to pass in the widget as well.

However, that then means that every *usage* of the handler is different - for example, the Cocoa button press handler currently invokes `self.interface.on_press(self.interface)` - and passing `self.interface` as an argument is the redundancy that we're trying to avoid.

You've *partially* addressed this - the handlers for GTK's table and tree widget are doing the right thing... but there's no point landing this PR until the same change has been made consistently throughout the entire codebase.

**Comment by MuhammadMouradG** [comment]
> The giveaway is the `widget=interface` argument on L60 on `wrapped_handler`. There shouldn't be any need for that argument - the whole purpose of `wrapped_handler()` is to build a closure of the widget over the handler method. If we're building a closure, we don't need to pass in the widget as well.

So, we can say that `warpped_handler()` create a **closure scope** and returns the `_handler` function that keeps this scope alive even `warpped_handler()` exits. Is this true?

**Comment by freakboy3742** [comment]
Mostly correct (although I suspect it's more a matter of terminology). `wrapped_handler()` creates a closure over `interface`. That closure is a function matching the definition of `_handler`. That closure will exist as long as a reference to the handler function exists.

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
This is now headed in the right direction, but it's still incomplete. For example, this will break on macOS, because all the existing references in the cocoa backend that invoke handler functions are explicitly passing in the widget (which is no longer required).

You'll also want to pay attention to the `NativeHandler` handling; this is what makes some of the macOS default menu items work.

**Comment by MuhammadMouradG** [comment]
> You'll also want to pay attention to the `NativeHandler` handling; this is what makes some of the macOS default menu items work.

I browsed the code but I can not figure out how the `NativeHandler` is affected, @freakboy3742 can give me an example, please?

**Comment by freakboy3742** [comment]
What I'm drawing attention to is the fact that `wrapped_handler`, processes handlers, and has 2 return paths - one for native handlers, and one for "normal" handlers. This PR is proposing to change the prototype of "normal" handlers, so I want to make sure that there aren't any side effects on the operation of native handlers. 

Native handlers are currently only used by macOS, and only then for a handful of menu items in the app menu (Show All/Hide Others et al).

It's possible there may be no effect at all; I just wanted to put this on your TODO list of edge cases that need to be checked.

**Comment by MuhammadMouradG** [comment]
Well, I can confirm that there is no effects, by my understanding, on the operation of native handlers.

**Comment by MuhammadMouradG** [comment]
@freakboy3742 is this PR still need changes?

**Comment by MuhammadMouradG** [comment]
Close this for inactive review status for long time and I don't able to maintaining this PR for long time.

If it is still interesting, please, let me know.

**Pull request closed without merging**
