### PR TITLE
Remove Android test discovery workarounds

### PR DESCRIPTION
**Pull request by mhsmith**
They're no longer needed now that extractPackages is in the Android template.

Requires https://github.com/beeware/briefcase-android-gradle-template/pull/60: DO NOT MERGE this PR before that one.

I've also added an `extractPackages` line for `toga_android`, which should allow #1707 to remove the code that disables coverage on Android. 

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by mhsmith** [comment]
CI will have to be rerun once https://github.com/beeware/briefcase-android-gradle-template/pull/60 is merged.

**Review by freakboy3742 — APPROVED** [review]
I initially had some difficulty getting this working on Py3.10 ([log file](https://github.com/beeware/toga/files/10462570/briefcase.2023_01_20-08_51_41.run.log)); but after stepping away and coming back to it, I can't reproduce that failure. I'm guessing I had something stale in my environment, but I can't work out what.

Otherwise - seems to work well.

**Comment by freakboy3742** [comment]
I've merged up the macOS-probe changes, which also means we now have a coverage report on Android. There is a workaround required because of nedbat/coveragepy#1542.

**Comment by mhsmith** [comment]
> I initially had some difficulty getting this working on Py3.10 ([log file](https://github.com/beeware/toga/files/10462570/briefcase.2023_01_20-08_51_41.run.log)); but after stepping away and coming back to it, I can't reproduce that failure. I'm guessing I had something stale in my environment, but I can't work out what.

OK, I've reproduced this now: see https://github.com/chaquo/chaquopy/issues/777.

**Comment by mhsmith** [comment]
I've fixed an issue with the coverage workaround which was crashing the test thread on desktop platforms, and added a top-level exception handler so the app will exit in such cases rather than hanging forever.

**Review by freakboy3742 — APPROVED** [review]
Those changes all make sense to me; 👍

**Pull request merged**
