### PR TITLE
Add handling for INS, DEL, NUM LOCK, and some shifted characters.

### LINKED ISSUE #2220: Missing GDK key definitions
### Describe the bug

Several keys are throwing the error below:
```
Traceback (most recent call last):
  File "/home/russell/.pyenv/versions/briefcase-3.10/lib/python3.10/site-packages/toga_gtk/widgets/textinput.py", line 29, in gtk_key_press_event
    key_pressed = toga_key(user_data)
  File "/home/russell/.pyenv/versions/briefcase-3.10/lib/python3.10/site-packages/toga_gtk/keys.py", line 228, in toga_key
    key = GDK_KEYS[event.keyval]
KeyError: 65436
```

Affected keys:
left shift: 0xFFE1
left ctrl: 0xFFE3
left alt: 0xFFE9
right shift: 0xFFE2
right alt: 0xFFEA
right super: 0xFFEC
right context: 0xFF67
right ctrl: 0xFFE4
insert: 0xFF63
...as well as the entire numpad (whether or not numlock is enabled)

### Steps to reproduce

Use the number pad in a `TextInput` using GTK.

### Expected behavior

The keys are mapped correctly.

### Screenshots

_No response_

### Environment

- Operating System: pop os 22.04
- Python version: 3.10.13
- Software versions:
  - Briefcase: `0.3.17.dev54+g39040475.d20231112`
  - Toga: `0.4.1.dev19+g69fc00cb5`

### Logs

[briefcase.2023_11_11-20_21_13.dev.log](https://github.com/beeware/toga/files/13326905/briefcase.2023_11_11-20_21_13.dev.log)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by freakboy3742**
Adds some missing key definitions for INSERT, DELETE and NUMLOCK, and some other esoteric keys; and improves shift handling for GTK.

Fixes #2220.

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Review by rmartin16 — COMMENTED** [review]
These work; although, do you want to handle CTRL, ALT, and SUPER similarly to shift? I still see those warnings.

Also, when I tab to the Calculate button in Tutotial1 example, I get a system beep. Is that expected?

**Comment by freakboy3742** [comment]
> These work; although, do you want to handle CTRL, ALT, and SUPER similarly to shift? I still see those warnings.

I've just added handling for these.

> Also, when I tab to the Calculate button in Tutotial1 example, I get a system beep. Is that expected?

... it is not. Bother. It was being masked in my testing because my VM didn't have its "speaker" attached.

**Comment by freakboy3742** [comment]
The beep appears to be pre-existing... I've opened #2554 to track it.

**Review by rmartin16 — COMMENTED** [review]
One more interesting one...if I hold CTRL or ALT and then press SUPER, I can still get the warning for SUPER...not necessary a common combo but it is used by window placement mgmt.

Also, just as note, noticing that the ALT+TAB icon is using the system default on Ubuntu and Fedora....may just be a Gnome thing though.

**Comment by freakboy3742** [comment]
The CTRL+ALT+WIN key combo appears to be coming through as a completely different key, rather than a combination of the three individual keys - but you *can* bind to `MOD_1+MOD_2+MOD_3+a`. 

Based on [the GTK docs](https://docs.gtk.org/gdk3/flags.ModifierType.html), all this handling is a bit abstract anyway, because it can be redefined at the X11 level - I'm guessing that is what is happening here. 

Rather than try to chase our tail here, I've opted to add a generic "If unknown, be quiet" handler; this only impacts on the key handling in TextInput, so I think we're OK to ignore weird combos.

**Review by rmartin16 — APPROVED** [review]
This tradeoff makes sense. fwiw, looks like Android also just ignores undefined keys.

**Pull request merged**
