### PR TITLE
Update location.py

### PR DESCRIPTION
**Pull request by kloknibor**
Added methods to Toga for enabling significant location change tracking, allowing the system to provide updates only when a significant change in location occurs. The methods start_significant_tracking and stop_significant_tracking manage starting and stopping this feature.

This change enables applications built with Toga to monitor significant location changes, improving efficiency for use cases that do not require constant high-resolution tracking. It can help conserve battery and optimize processing by triggering updates only on substantial location changes, while still supporting background processing capabilities.

## PR Checklist:

- [ ] All new features have been tested
- [ ] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by mhsmith** [comment]
Please answer the following questions which were in the PR template:

* Describe your changes in detail
* What problem does this change solve?

The [documentation of this API](https://developer.apple.com/documentation/corelocation/cllocationmanager/startmonitoringsignificantlocationchanges()?language=objc) says:

> Apps can expect a notification as soon as the device moves 500 meters or more from its previous notification. It should not expect notifications more frequently than once every five minutes.

That's a significant reduction in both space and time resolution compared to the current API, and it's not clear why it would be useful. But if there is a use case, it should be incorporated into the public Toga API, and not left as an undocumented iOS-only feature.

**Comment by kloknibor** [comment]
i have added my motivation, basically I am building a location recording app, however since this should be tracking the location in the background continuously it would be a lot better on the battery to use the significant location change function of ios vs the high resolution GPS one.

**Comment by freakboy3742** [comment]
> i have added my motivation, basically I am building a location recording app, however since this should be tracking the location in the background continuously it would be a lot better on the battery to use the significant location change function of ios vs the high resolution GPS one.

Sure - that motivation makes sense. However, there's a long way between that idea, and the PR that you've provided here.

First: some initial housekeeping: the PR is failing 2 CI checks. Our [contribution guide](https://toga.readthedocs.io/en/stable/how-to/contribute/code.html#submitting-a-pull-request) gives some pointers on how to set up your local development environment to pre-check those issues, and the other requirements that exist for a pull request.

Second: Toga requires tests and documentation for all code that is contributed. This is mentioned in the contribution guide, and it would also be picked up by CI once the initial CI failures have been addressed. We have 100% code coverage in our test suite - so any new code that is added without adding tests will fail CI.

Lastly - and most importantly: while you've added 2 methods to the API of the iOS backend, that's a long way from this feature being complete. Even if we were to merge this PR, you wouldn't actually be able to use it, because there's no public API surface for the feature in the core location API. That API needs to be designed and added. That requires some consideration of what location management features are available on other platforms (most notably, Android). That doesn't mean you need to *implement* those features on all platforms - but we need to have at least some confidence that what has been proposed *could* be implemented in a cross-platform way. That usually means doing some research on the capabilities and APIs of all affected platforms.

**Comment by kloknibor** [comment]
Allright, all valid points, when I find some time I will look into properly contributing this functionality. For now I'll close the PR to not clutter this space ;-)! Thanks!

**Pull request closed without merging**
