### PR TITLE
Fix horizontal scrollbar

### PR DESCRIPTION
**Pull request by MuhammadMouradG**
## Describe your changes in detail
This PR fix the issue of the horizontal scrolled window

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
It's not at all clear what you're doing with this patch, or what "the issue" you're proposing to fix actually is. You appear to have changed the ordering in which horizontal and vertical attributes are declared... but it's not clear to me at all why that would impact anything. 

Can you describe what the underlying "issue" actually is - and possibly reframe this diff so that the changes are minimal, rather than arbitrary code reorganisations?

**Comment by MuhammadMouradG** [comment]
Of course, I am sorry for that. I changed the code ordering to the code be easy to track for debugger; first attribute declare invoke the first function declare. 
The critical change actually was the `self` parameter in function `getattr()` which replaced by parameter `self.interface` in `def set_horizontal(self, value)` and `def set_vertical(self, value)` with preserve other parameter for each one:

`Gtk.PolicyType.AUTOMATIC if getattr(self, 'horizontal', not value) else Gtk.PolicyType.NEVER`
`Gtk.PolicyType.AUTOMATIC if getattr(self.interface, 'horizontal', not value) else Gtk.PolicyType.NEVER` 

After that change the line was long and this is what making me break the line.

**Comment by freakboy3742** [comment]
Ok; that makes more sense. 

It *really* helps if you submit pull requests from a branch, rather than your master. It avoids the problem you're seeing on #1059, where one PR is dependent on another; plus, if there's some minor tweak that I want to make before merging a change, I can do that; I can't edit your master branch.

In this case, the `getattr()` construction is messy - but it's also something that can be easily removed. It's only required because the interface layer doesn't have a value for `_horizontal` and `_vertical` when the widget is originally set up. If you add:

        self._vertical = vertical
        self._horizontal = horizontal

prior to creating `_impl` in the interface layer, the GTK implementation can reference `self.interface.horizontal` without any problem. That also avoids the really hard to read 6-line block of inline if statements :-)

If you want to make this change on your own and update the PR, I'll merge; alternatively, if you can re-open this PR from a branch other than your master, I'll happily make the change on my own.

**Comment by MuhammadMouradG** [comment]
I created branches to solve this problems, and this will be last one editing from the `master`, ISA.

In fact, adding:
```python
self._vertical = vertical
self._horizontal = horizontal
```
to the interface is really what was I trying to do, but the problem was that this will not lead to change the scroll-ability of window when 
```python
toga.ScrollContainer(horizontal=False, content=right_content)
```
is invoked in code

**Comment by MuhammadMouradG** [comment]
I update the files, and this will be the last PR from the master, ISA.

**Review by freakboy3742 — APPROVED** [review]
Fantastic - thanks for the fix!

**Pull request merged**
