### PR TITLE
Set correct value of `MultilineTextInput.readonly` for iOS.

### PR DESCRIPTION
**Pull request by o-fedorov**
On iOS, `MultilineTextInput` is read-only by default and when `readonly` is `False`, and editable when `readonly` is True.

Fixes https://github.com/beeware/toga/issues/1859

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by o-fedorov** [comment]
I would appreciate if you suggest how to add tests for this change.

**Comment by freakboy3742** [comment]
@o-fedorov This is an area where our docs are a bit slim, so I've just added a PR (#1868) to add details on how the testbed app and backend tests work. You can see a preview of these docs [here](https://toga--1868.org.readthedocs.build/en/1868/how-to/contribute-code.html#running-the-testbed).

At present, there aren't any backend tests for MultilineTextInput, so any improvement here will be a win. If those docs don't make any sense, or you can't work out how to build a test for readonly, let us know - we can merge what you've got here so you're unstuck on the specific bug. We're in the process of auditing all the widgets, so we should be adding tests fairly soon.

**Comment by o-fedorov** [comment]
@freakboy3742 thank you for the response. I have created a copy of this PR with tests added: https://github.com/beeware/toga/pull/1869

Feel free to do anything with these PRs, like close this one and update the other PR.

**Comment by freakboy3742** [comment]
Thanks - I'll close this in favour of #1869, since that looks pretty close to being merge ready.

**Pull request closed without merging**
