### PR TITLE
Added MIDIPlayer for iOS and macOS

### PR DESCRIPTION
**Pull request by isaingard**
Signed-off-by: Isaiah Hewitt <isaiah@hewitts.us>

Implemented the [AVMIDIPlayer](https://developer.apple.com/documentation/avfoundation/avmidiplayer) as MIDIPlayer for iOS and macOS.

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by isaingard** [comment]
Thanks for the feedback!  I'll add some docstrings describing the MIDIPlayer attributes and make the changes requested.  Regarding the API design, I'll do some research into Android and Windows MIDI players and see how they work.

The rate property is a property of the playing, and it can be adjusted while the MIDIPlayer is playing.  It acts as a multiplier on the original tempo of the MIDI sequence.

The sound interface for playing a MIDI file on iOS and macOS is nearly identical to the sound interface for playing a mp3 or wav.  I think the code could be basically copy-pasted with only a few differences in class names and initialization.

Here is some example code for the MIDIPlayer.
```
midi_data = open(self.app.paths.app / 'resources' / 'Deck the Halls.mid', 'rb').read()
sound_font = self.app.paths.app / 'resources' / 'piano.sf2'
midi_player = toga.MIDIPlayer(midi_data, sound_font=sound_font)

midi_player.play()
# midi_player.current_time = 10
# midi_player.rate = 1.4
```
The MIDI file and soundfont I used are attatched.

[MIDI example.zip](https://github.com/beeware/toga/files/4921022/MIDI.example.zip)

**Comment by isaingard** [comment]
I made the requested changes and removed the empty TogaMIDIPlayer classes and unused AVAudioSession classes.  The AVAudioSession classes were used to make music play in silent mode on iOS by calling "AVAudioSession.sharedInstance().setCategory_error_(AVAudioSessionCategoryPlayback, None)", but this isn't used anywhere in the toga code base, so I removed the classes.  I also added docstrings based on the way they were added in core/button.py.  

I did some research into Android and Windows MIDI players.  Android has a [MediaPlayer](https://developer.android.com/guide/topics/media/mediaplayer) class, which can play many different kinds of audio files, [including MIDI](https://stackoverflow.com/questions/56541361/android-play-soundfont-with-midi-file).  It looks like it is able to perform all the operations of the MIDI player I implemented.  Windows was a little messier as it uses something called [MCI](https://docs.microsoft.com/en-us/windows/win32/multimedia/mci-reference) (Media Control Interface) to play sounds.  MCI is capable of [playing MIDI files](https://docs.microsoft.com/en-us/windows/win32/multimedia/playing-midi-files), and it looks to be capable of all the operations of the MIDI player I implemented.

Regarding your concerns about the MIDIPlayer's API only playing one MIDI sample, I made a function (set_sample) that can change the MIDIPlayer's data to a different sample without leaking memory.  It is now able to change it's sample and play samples simultaneously.

I read about Pygame's midi module, and it looks like a MIDI (Musical Instrument Digital Interface) module, made for "interacting with MIDI input and output".  On the other hand, my MIDIPlayer is meant to be an audio player specifically for MIDI files (as opposed to MP3 or WAV).

**Comment by freakboy3742** [comment]
The issue I'm having is still one of nomenclature. The fact that the API is called "MIDIPlayer" on iOS/macOS doesn't mean we need to use the same name - especially if a different naming scheme will make it easier for people to understand how to use the API.

The "widget" being defined here is a "Player" - to me, a "player" is a "device" that plays a "sound", not a thing that *is* the sound to be played. 

The analogy is similar to Image vs ImageView - there's the image itself, and the widget you use to display an image. You can change the Image that the ImageView is displaying, and you can load an image without necessarily displaying it. The Image itself can be PNG, GIF, JPG or whatever; and an ImageView can display any Image, in any format.

Following that metaphor, there's something that *plays* the sound, and there's a wrapper around the sound data itself. The sound data could be MIDI, or a WAV, or MP3; but whatever the sound is, it can be "played" by the "Device/Player" widget.

Alternatively, maybe the "device" metaphor isn't needed here - we just need the "sound", which can be played, paused etc. We need to control where an Image is displayed, but there's only one audio output where a sound can be produced. In that case, then maybe renaming MIDIPlayer to `MIDITrack` or `MIDISample` is all we need. In the future, when we add MP3 or WAV support, we add `MP3Track` or `WAVTrack` objects that can also be played (using whatever mechanism is required).

That said, my understanding was that MIDI had support for multiple MIDI outputs; so maybe there *is* a need for a "device" representation.

**Comment by isaingard** [comment]
Ok, makes sense.  I changed the class name to MIDITrack.

**Comment by freakboy3742** [comment]
While this is functionally complete, the API still doesn't seem right. I'm not sure it makes sense for a Track to be a standalone object - and one whose content is mutable. 

Thanks for the contribution; however, I think this needs to be part of a larger design discussion about APIs for generating sound.

**Pull request closed without merging**
