### PR TITLE
Update all development dependencies

### PR DESCRIPTION
**Pull request by rmartin16**
## Changes
- Dependabot is seemingly unable to update dependencies if a directory contains both a `setup.cfg` and `setup.py`
- Currently the dependencies are about 9 months out of date....this brings them all to their latest version

## PR Checklist:

- [X] All new features have been tested
- [X] All new features have been documented
- [X] I have read the **CONTRIBUTING.md** file
- [X] I will abide by the code of conduct

### CODE REVIEW

**Comment by rmartin16** [comment]
well....this is much more interesting now. pre-commit is failing on running this version of black in CI....

**Comment by freakboy3742** [comment]
/me grumbles... Github will send me three emails to notify me that someone has commented on a PR, and will email me when *I* comment on a ticket, but *won't email me when an automated process fails*....

**Comment by rmartin16** [comment]
Was finally able to replicate locally....might have something to do with Python 3.12.

Nonetheless, I looked at the file it was complaining about:
```
# Note that we recommend using https://github.com/psf/black-pre-commit-mirror instead
# This will work about 2x as fast as using the hooks in this repository
- id: black
  name: black
  description: "Black: The uncompromising Python code formatter"
  entry: black
  stages: [pre-commit, pre-merge-commit, pre-push, manual]
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  types_or: [python, pyi]
- id: black-jupyter
  name: black-jupyter
  description:
    "Black: The uncompromising Python code formatter (with Jupyter Notebook support)"
  entry: black
  stages: [pre-commit, pre-merge-commit, pre-push, manual]
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  types_or: [python, pyi, jupyter]
  additional_dependencies: [".[jupyter]"]
```

Given the top two lines, I switch the config to use the mirror and things seem to be working now....

**Comment by rmartin16** [comment]
FWIW, the "we" that is making this recommendation is apparently the maintainers of black....since this file comes from its repo: https://github.com/psf/black/blob/main/.pre-commit-hooks.yaml

**Comment by rmartin16** [comment]
ohhh....the version of pre-commit that Toga uses is 9 months....i'm guessing Dependabot doesn't recursively look for setup.cfg files...???? or is something intentional going on here?

**Comment by freakboy3742** [comment]
> ohhh....the version of pre-commit that Toga uses is 9 months old....I'm guessing Dependabot doesn't recursively look for setup.cfg files...???? or is something intentional going on here?

Definitely nothing intentional; I can't explain why pre-commit isn't being updated.

**Comment by rmartin16** [comment]
Dependabot isn't updating anything in `core/setup.cfg`....all of the dependencies are out of date:

https://github.com/beeware/toga/network/updates/748619508

I wonder if it's only checking `setup.py` and moving on or something....

**Comment by freakboy3742** [comment]
Hrm - I wonder if this is a case of having setup.py confusing the setup - if we moved to a setup.cfg-only configuration, it wouldn't think that the configuration is in setup.py, and therefore miss that all the dependencies are in setup.cfg.

**Comment by rmartin16** [comment]
Yep; I just duplicated the toga repo, deleted `core/setup.py`, re-ran Dependabot and it created several PRs until it logged  "Dependabot cannot open any more pull requests".

I'll just manually update everything in this PR for now to reset us.

**Review by freakboy3742 — APPROVED** [review]
Can't argue with CI success.

**Pull request merged**
