### PR TITLE
Implementation of ScrollContainer for Android

### PR DESCRIPTION
**Pull request by t-arn**
This PR implements ScrollContainer for Android
I also extended the scrollcontainer example with Switches to turn scrolling on and off.

## PR Checklist:

- [x] All new features have been tested
- [ ] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct
Screenshot_1608118341

### CODE REVIEW

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
Looks good! Three high level notes:

1. The explicit "if android" case in the demo is something we generally try to avoid; I completely understand why you've done it (otherwise the demo wouldn't work), but I'd prefer to avoid committing it as a permanent part of the demo - mostly because there won't be any meaningful reminder to go back and remove it later. In this case, the divider doesn't actually add much to the demo, so I'd be fine with removing it - or, if you wanted to go for a twofer and implement Divider as well... :-)
2. There's a lot of stray print statements; those are great for debugging while you're developing, but they're going to end up being noise for the end user. We should probably comment them out or delete them.
3. One small cosmetic detail (that I'm guessing will actually end up being the hardest to fix) - I noticed that the horizontal scroll bar is only visible when you're at the bottom of the scrollable area. I can't get a screenshot because the scrollbar only displays when you're scrolling - but if I scroll when I'm at the "top" of the page, I don't see the horizontal scroll bar. I only see the horizontal scroll bar when it appears over the top of the "item 99" line. Strangely, this *doesn't* affect the vertical scrollbar - that seems to appear regardless.

**Comment by t-arn** [comment]
I removed the Divider and the print statements.

As for the horizontal scrollbar: You are right! I did not spot that before. 
The reason is that the horizontal scroll is outside the visible area. 
I changed the number of rows to 34, so all rows are in the visible area and then, the horizontal scrollbar is visible from the beginning.

I believe that the Android viewport is miscalculated, maybe because the top title bar is not taken into account (correctly)?

**Comment by t-arn** [comment]
By the way: I found a very bad behavior on Windows:
When I click into the scrollbars, everything is fine.
But when I click and **drag** the scrollbars, the app becomes **EXTREMELY** slow and unresponsive.
You don't have a Windows machine to confirm this, do you?

**Comment by freakboy3742** [comment]
It's entirely possible that the overall window height has been calculated incorrectly; however, that doesn't explain the behavior that we're seeing here. If the issue was purely one of the overall window size being computed incorrectly, then you'd *never* see the horizontal scrollbar, as it would be rendered "below" the bottom of the visible window. The fact that the scroll bar *is* visible as long as you scroll to the bottom means that the bottom of the widget is at the bottom of the screen; but the scrollbar is being rendered inside the scrollable area, not the containing area.

Looking closer at the code, that's exactly what is happening - you've added the horizontal scroll area *inside* the vertical scroll area - so the horizontal scroller will only be visible when the bottom of the vertical scroll area is visible. 

As for the scrolling lag problem on windows; I don't observe that in my testing. For full disclosure, I'm running Windows in a VM on a Mac - but I'd expect that to make any lag problems *more* extreme. I do see some double-buffering style display corruption if you scroll quickly, but those rendering problems are fixed as soon as the scrolling stops.

**Comment by t-arn** [comment]
I created a native example (see https://bitbucket.org/TomArn/androidexample.git  branch: scrollcontainer) and there is also this problem with the horizontal scrollbar :-(
So, it is not a beeware problem as I thought...
I found some posts on the Internet from users who had the same scrollbar problem with their native apps, But I have not found a good solution so far. Most answers said that scrolling in both directions should be avoided by design.

There is an Android class NestedScrollView - maybe, this class will solve the problem.

**Comment by freakboy3742** [comment]
It's definitely a limitation of `VerticalScrollView` and and `HorizontalScrollView` in the way you're using them; but it can't be a limitation of *Android*. Consider, for example, WebView - it has horizontal and vertical scroll bars visible at the same time. I have no idea how that is implemented, but it's worth some further investigation.

However - a working but imperfect something is better than a perfect but theoretical nothing. If you can't find an obvious fix or workaround, I'm inclined to accept this PR as is, and open a ticket declaring the horizontal scrollbar problem as a known issue that can be addressed as future work. That allows developers to use the *Toga* feature right now on Android, and we can improve the implementation with time.

**Comment by t-arn** [comment]
I googled some more and found that there are several custom implementations for the missing 2-dimensional-scrollview in Android, e.g. this one: https://github.com/lucasr/twoway-view/
But I wouldn't know how to make this work with beeware. Can it be done?

I have not found any other slick solution for the missing horizontal scrollbar so far.
Maybe, someone else can solve this problem.
If not, I agree that we should go with this solution for the time being.

**Comment by freakboy3742** [comment]
I will admit that I'm not an Android expert, but that TwoWay View seems to be solving a different problem - grids of sub-containers that are "recycled"; scrolling would seem to be an almost unintentional side effect. View recycling is a common way of handling things like DetailView, where each cell in the list/grid is a distinct view with it's own layout, and you don't want to instantiate an instance for every item in the list - only the items that are visible.

The one approach that I've seen come up multiple times (but is hard to find because the original link is down) is [this one (retrieved via the wayback machine)](
https://web.archive.org/web/20130305091318/http:/blog.gorges.us/2010/06/android-two-dimensional-scrollview). It's long, but looks like it ties into the primitives at a lower level. Porting this to Python won't be a small job, so I'd be happy deferring this to a future improvement ticket.

That said: in the comments on that blog post, the original author points at [this approach](https://stackoverflow.com/a/8035250/218383) as a better implementation; this is much closer to what you've implemented, but with a couple of key differences - in particular around the application of layout parameters in the outer view, and the handling of touch events. The handling of touch events appears to be needed to allow for "diagonal" scrolling. I'd be interested to see if those relatively minor changes get us to the goal without needing to implement 1000 lines of Java-in-Python.

**Comment by t-arn** [comment]
Yeah, I saw this post myself during my research, but how do we implement derived java classes in Python?

**Comment by freakboy3742** [comment]
@t-arn Ah - I missed that there was subclassing involved. That's a problem for Rubicon at present. 

However, the subclassing is only required to get "diagonal" scrolling; the other difference is the alteration to the layout parameters (using `WRAP_CONTENT` rather than `MATCH_PARENT`). That seems like something that might alter how the "inner" container is displayed, which would in turn affect the visibility of the horizontal scrollbar.

**Review by freakboy3742 — APPROVED** [review]
Ok - on the basis that the perfect is the enemy of the good, I'm going to merge this as is. There's definitely room for further improvement (diagonal scrolling, and the position of the horizontal scrollbar), but this at least gets a basic working ScrollContainer in place. 

Thanks for the contribution!

**Pull request merged**
