### PR TITLE
Fix javascript compatability of Webview

### PR DESCRIPTION
**Pull request by Ksengine**
## Fixed
system native webviews are old and less featured webviews.
they arn't work finely with modern browsers.
as you can see browser compatibility tables of javascript references in `mozilla.org`

## solution
I had created a simple js polyfill to fix them.
I am openning this pr to add it to toga.
- polyfill is injected to toga Webview every time before load each website.
- It modifies built-in javascript objects and methods.
- then javascript on website can use them freely.

this is like jQuery. but not a tool that have API to used by developers. Just modifies built-in APIs.
Write the codes with vanilla js.

## edited files
- added new file photon.py
converted minified photon.js library to single line python code and included.
- edited core webview.py to inject js code.

## more
Photon fixes following features
- XmlHTTPRequest - ajax polyfill(need some more patches)
- String.trim()
- Array.isArray()
- Array.forEach()
- Array.map()
- Array.filter()
- Array.reduce()
- Array.reduceRight()
- Array.every()
- Array.some()
- Array.indexOf()
- Array.lastIndexOf()
- JSON.parse()
- JSON.stringify()
- Date.now()

- "use strict" - (Hope todo)
- Property Getters and Setters(Cannot impliment)
- New Object Property Methods(TODO)

# :star2: Photon
- Star Photon - [GitHub Repo stars](https://github.com/Ksengine/Photon)
- Contribute - [GitHub Repo forks](https://github.com/Ksengine/Photon/fork)

## PR Checklist:

- [ ] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
Two questions:

1. Why would we use photon.js, rather than an established polyfill framework like polyfill.io?

2. I have *repeatedly* asked for you to provide a testing plan with PRs. HOW DO I VERIFY THAT THIS WORKS?

(2) is especially important in this case, because I literally can't see how it can work. You're catching Toga's own internal on_load message - which triggers *after* the page has loaded, so you'll be injecting the polyfill *after* the page has loaded.

**Comment by Ksengine** [comment]
> Why would we use photon.js, rather than an established polyfill framework like polyfill.io?

It's huge. it has many files and I can't generate local single file from it.

**Comment by Ksengine** [comment]
> I have repeatedly asked for you to provide a testing plan with PRs. HOW DO I VERIFY THAT THIS WORKS?

sorry, I can provide.

**Comment by Ksengine** [comment]
> (2) is especially important in this case, because I literally can't see how it can work. You're catching Toga's own internal on_load message - which triggers after the page has loaded, so you'll be injecting the polyfill after the page has loaded.

can we change it.
- onload = on load start
- onshown = when loading ended

**Comment by freakboy3742** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
