### PR TITLE
Added support for cursor visibility in WinForms.

### PR DESCRIPTION
**Pull request by proneon267**
Added support for cursor visibility in WinForms for the existing APIs. As discussed, implementation was done under existing API and no new API was added. A shadow variable was needed as the calls to show and hide cursor needs to be balanced.
## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by proneon267** [comment]
@freakboy3742 Does this need some changes, or is it good?

**Comment by freakboy3742** [comment]
This is on my list to look at; however, given the issues with #1895, I want to actually test this myself on Windows before merging, and I won't get a chance to do that until I'm back at work next week.

**Comment by proneon267** [comment]
> This is on my list to look at; however, given the issues with #1895, I want to actually test this myself on Windows before merging, and I won't get a chance to do that until I'm back at work next week.

Thanks. Take your time :)

**Review by freakboy3742 — APPROVED** [review]
I've added a manual test case, but otherwise this looks good.

**Comment by proneon267** [comment]
> I've added a manual test case, but otherwise this looks good.

Thanks :)

**Pull request merged**
