### PR TITLE
Add initial Android DetailedList

### PR DESCRIPTION
**Pull request by paulproteus**
It is missing swipe-to-delete, scroll-to-refresh, and on_press handlers for now.

Those are all ready in my Java version; porting them to Python is taking longer than I hoped.

I am hopeful we can merge this to satisfy my desire to get some code off my chest.

## Screenshot

image

## Next steps

I plan to add swipe-to-delete first, then on_press handlers, then scroll-to-refresh. Note that scroll-to-refresh will require an update of the Android app template to include a tiny (~100KB) Google-brand Android library.

## PR Checklist:
- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by paulproteus** [comment]
(and if we can't merge it yet due to layout bugs/etc, I'd be happy to know that, too.)

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
The code that is here looks fairly straightforward; and it mostly seems to work fine, too. 2 questions/clarifications:

Firstly, the "destroy everything and re-build" approach seems... a little overkill. I totally understand that it's the easiest solution; how much work is involved in a "delta" based approach?

Secondly, there's something odd going on with the scrollbar rendering. Unfortunately, the best way I can demonstrate is with a photo of my screen...
IMG_9074

So: it looks like the "pull down to scroll" indicator is full width; but the scroll bar isn't at the edge of the screen; and if I look *really* closely, it looks like the background of the rows doesn't expand full width (although it *does* match the location of the scroll bar). Is there something going on there?

**Comment by paulproteus** [comment]
> Firstly, the "destroy everything and re-build" approach seems... a little overkill. I totally understand that it's the easiest solution; how much work is involved in a "delta" based approach?

The honest answer is I don't know yet.

I don't see straightforward platform-native way to do that -- fundamentally, this can't be a normal native list view because those don't have the swipe-to-delete behavior.

Hypothetically, there are a few options for making it more efficient, but I haven't written code for any of them yet.

- Python can look for the relevant row(s) (as child "Views") in the `dismissable_container` `LinearLayout`, then modify the objects accordingly. I'm nervous about introducing a bug where the user deletes row 7, then swipes to delete row 8, and in fact the underlying row 9 gets deleted. This seems "not that hard", but probably adds 20-40 lines of code that have to be written very thoughtfully.

- Python can get the current state from Java when some data changes, then do a diff and merge. It'll mean more trips across the (...rubicon...) bridge. This is like a dumber, more fearful version of the previous option. Maybe the previous option is just better. :)

- I can learn about the Android "RecyclerView" concept, but I'm still not sure it would apply in this case without lots of really careful code. This is an Android native way to allow you to avoid painting the full set of rows... but it's a lot of Android API surface to use this, which I haven't explored yet honestly.

I'm a little loathe to implement any of that complexity right now.

I'd like to see all the functionality satisfactorily merged first before embarking on that.

> Secondly, there's something odd going on with the scrollbar rendering. Unfortunately, the best way I can demonstrate is with a photo of my screen...

I can repro this -- it looks like there's a different color background for me to the right of the scrollbar. Good catch!

image

In my fully-featured Java version, this issue doesn't exist. I propose you permit me to get this merged as-is, and we revisit once pull-to-refresh is added. I suspect it'll go away once I add that library. Check out this screenshot.

Screen Shot 2020-08-26 at 11 19 35 PM

If it doesn't go away then, then I can dig deeper then.

Semi-sorry to just keep requesting to kick these cans down the road. Let me know if you'll accept this temporary pausing point as a place for further pull requests to revise things further. I think that we can get this fixed, but I don't think it makes lots of sense to do so until all the features are in.

**Comment by paulproteus** [comment]
re: scrollbar weirdness:

One related problem is that I'm probably using the platform default background color, not the background color of the current theme. That's something that I'm game to fix before you merge this, if it's important to you. (Otherwise I can submit a follow-up pull request, which is my preference.)

**Comment by freakboy3742** [comment]
If there isn't an obvious solution for optimising the refresh process, I'm happy to live with a "complete rebuild" for now, on the "perfect is the enemy of the good" principle. I was vainly hoping that the LinearLayout might sufficiently list-like that "delete item 3 from the data" might translate to a "delete item 3 from the layout" call. If that's not the case, I'm happy to leave that for future explorers to optimize.

As for kicking down the road... I guess that's fine. We already know there's going to be at least one more DetailedList PR, so if you have reason to believe that the swipe action might fix that layout problem too, I'm happy to defer.

**Review by freakboy3742 — APPROVED** [review]

**Comment by paulproteus** [comment]
Gonna leave myself a little todo list here

Soonish

- [ ] Use theme background, not generic background, in DetailedList
- [ ] Add ontouch (aka onclick/onpress) handlers
- [ ] Add swipe to refresh library to template
- [ ] Rely on swipe to refresh library for swipe to refresh in DetailedList, i.e., implement on_refresh
- [ ] Add anything else as needed to this todo list

A while later probably, maybe never

- [ ] Stop doing a full rebuild of the layout on every data change

**Pull request merged**
