### PR TITLE
Fixed update/init with padding

### PR DESCRIPTION
**Pull request by HalfWhitt**
One more cleanup from #3033. `padding` and its children worked fine when being *set*, but `Pack(padding=1)` or `style.update(padding=1)` still threw an error. Fixed and tested.

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Review by freakboy3742 — APPROVED** [review]
Nice catch!

**Comment by HalfWhitt** [comment]
If only I'd caught it as part of the first PR!

One thing I've been noticing / thinking about... `BaseStyle` accepts hyphenated or underscored forms of its property names in `__init__`, `update`, and bracket notation; dot lookup is the *only* place it requires underscores. For consistency, would it be a good idea for Travertino's `__getattribute__` to also do the conversion?

**Comment by mhsmith** [comment]
It's not syntactically possible to use hyphens with dot notation, because they would be parsed as a subtraction operator.

In fact, I'm not really sure why we allow bracket notation and hyphenated forms at all. @freakboy3742: what's the use case for this?

**Comment by HalfWhitt** [comment]
> It's not syntactically possible to use hyphens with dot notation, because they would be parsed as a subtraction operator.

Oh right, duh 🤣 Brain fart moment there.

> In fact, I'm not really sure why we allow bracket notation and hyphenated forms at all. @freakboy3742: what's the use case for this?

I've always assumed the former is for easier dynamic application and retrieval of properties without lots of `settattr`/`getattr`, and and the latter is thinking ahead for CSS intake, I guess? Yeah, I'm curious too.

**Comment by freakboy3742** [comment]
> > In fact, I'm not really sure why we allow bracket notation and hyphenated forms at all. @freakboy3742: what's the use case for this?
> 
> I've always assumed the former is for easier dynamic application and retrieval of properties without lots of `settattr`/`getattr`, and and the latter is thinking ahead for CSS intake, I guess? Yeah, I'm curious too.

Yes - the hyphen form was to accomodate the "preferred" form of CSS directives.

I don't know that I have a *good* reason for including the bracket form and having `__setattr__`/`__setitem__` parity, other than "...well what else are you going to use `__setitem__` for?", and maybe a *weak* argument that it allows you to use hyphen notation for styles in "natural" Python syntax (i.e., `style["foo-bar"]` reads as more natural Python, as opposed to `setattr(style, "foo-bar", value)`).

**Pull request merged**
