### PR TITLE
Add background color to android box widget

### PR DESCRIPTION
**Pull request by Spitskool42**
Add background color to android box widget

Now you can also change the background color of boxes. This is an easy way to change the main background color from white to a color of choice (if you use a box as main).

Added set_background_color to the android box widget

Can change box background colors now.

Tested on android 11, lineageOS 18.1

## PR Checklist:

- [x] All new features have been tested
- [ ] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by mhsmith** [comment]
Thanks for the contribution, Actually, there's already a placeholder `set_background_color` method in widgets/base.py, so I think this code should go there. That would allow the color of *any* widget to be changed.

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
In addition to the point @mhsmith has raised, it's helpful if PRs that add new features like this one include a change to one of the example apps to demonstrate the feature (or identify one of the existing apps that demonstrates the feature has now been implemented on a specific platform). 

In this case, a demo already exists; the `box` demo demonstrates background colors on boxes and buttons; if this PR is being modified to be more generic, it might be helpful to modify the box example to include a label so that the generic background setting behaviour can be verified.

**Comment by Spitskool42** [comment]
I tested it in the widgets/base.py. This seems to work for in my application.
Be aware that the (android) button.py sets the background differently:
`self.native.getBackground().setColorFilter(native_color(value), PorterDuff__Mode.MULTIPLY)`
But this still seems to overwrite the base.py background color.

**Comment by Spitskool42** [comment]
@freakboy3742 @mhsmith I don't think we can use setBackground for all widgets. See my example above about the button. Android does some strange things when setting the background.
Another example: 
        testWidget = toga.TextInput()
        testWidget.style.background_color='red'

The TextInput widget will now change the background color to red, but also removes the bottom edit line below the text  (or also changes the color of the line) . What normally is shown under a default editText.

**Comment by freakboy3742** [comment]
True, we can't use `setBackground()` for all widgets - but we can use a default implementation and then disable or override on the widgets that need special handling (like Button does). The only reason to *not* do this is if there are more special cases than there are cases where the "default" behavior will work.

If you've got reason to suspect this sort of special handling will be needed for most widgets, then sure - it would make sense to associate this implementation with Box specifically. Some research may be needed here.

**Comment by mhsmith** [comment]
> The Box widget (RelativeLayout) does not have the android method `getBackground()`, but the button and textedit have.

`setBackgroundColor` and `getBackground` are both defined on the [`View`](https://developer.android.com/reference/android/view/View#setBackgroundColor(int)) class, so they're available for all widgets. As you've found, some widgets use the background feature to draw more complex things. Ideally we would identify all of these widgets and make them use `setColorFilter` to tint the existing background, rather than replacing it. But I think a default implementation that replaces the background is still an improvement over the status quo, so this PR doesn't need to do anything more complex, unless you want to.

**Comment by Spitskool42** [comment]
> > The Box widget (RelativeLayout) does not have the android method `getBackground()`, but the button and textedit have.
> 
> `setBackgroundColor` and `getBackground` are both defined on the [`View`](https://developer.android.com/reference/android/view/View#setBackgroundColor(int)) class, so they're available for all widgets.
> 
> As you've found, some widgets use the background feature to draw more complex things. Ideally we would identify all of these widgets and make them use `setColorFilter` to tint the existing background, rather than replacing it. But I think a default implementation that replaces the background is still an improvement over the status quo, so this PR doesn't need to do anything more complex, unless you want to.

Yeah, think so too. Only containers/boxes have no getBackground method I think. Will test and change it to include in base.py when I have more time.

**Comment by mhsmith** [comment]
@freakboy3742: Even if this PR only supports Box, it's already very useful for debugging layouts, so I think we should merge it as-is. I've tested it with examples/box.

I've made small update to treat a background color of None as TRANSPARENT, which is consistent with toga_winforms/box.py and examples/box/box/app.py.

**Pull request merged**
